# Mario Kart Tracker v2: Data Upload

The aim of this notebook is to enter data into the PostgreSQL database.

Using the CSV's produced in the data scraping section, this notebook will take them and upload the data to the database.

Required Libraries:
* `Pandas`
* `psycopg2`

In [ ]:
import pandas as pd
import psycopg2
from sqlalchemy import create_engine
from pathlib import Path

In [2]:
wd = Path()

In [ ]:
engine = create_engine('postgresql://postgres:postgres@localhost:5432/mk_tracker')

In [3]:
conn = psycopg2.connect(database="mk_tracker",
                        user="postgres",
                        password="postgres",
                        host="localhost",
                        port=5432)

conn.autocommit = False
cursor = conn.cursor()

## Inserting the Game Versions

We'll start by inserting the game versions. These are the most basic, and are required so that we can obtain the id's for other tables.

Since we don't have a CSV for that particular table, we'll just enter it manually.

In [4]:
game_df = pd.DataFrame(data=["Mario Kart 8 Deluxe", "Mario Kart World"],
                       columns=["name"])

sql = '''INSERT INTO game_version ("name")
         VALUES (%s)
         ON CONFLICT ("name") DO UPDATE SET "name" = EXCLUDED."name"
         RETURNING "game_version_id";'''

for i, row in game_df.iterrows():
    print(row["name"])
    cursor.execute(sql, (row["name"],))
    id = cursor.fetchone()
    print(id)

read_sql = "SELECT * FROM game_version"

cursor.execute(read_sql)
game_version_data = cursor.fetchall()

conn.commit()

game_version_df = pd.DataFrame(game_version_data, columns=[desc[0] for desc in cursor.description])

game_version_df

Mario Kart 8 Deluxe
(10,)
Mario Kart World
(11,)

   game_version_id                 name
0               10  Mario Kart 8 Deluxe
1               11     Mario Kart World

In [5]:
game_version_df.to_csv(wd / "data" / "game_version.csv", index=False)

## Characters

Now we will insert the characters. But first, we need to add in the id's of the games

In [24]:
character_df = pd.read_csv(wd / "data" / "characters.csv")
game_version_df = pd.read_csv(wd / "data" / "game_version.csv")

def combine_dfs(data_df, game_version_df, name_column, game_column):
    data_df = data_df.merge(game_version_df, how="inner", left_on=game_column, right_on="name")

    data_df = data_df.drop(columns=[game_column, "name"])

    data_df = data_df.rename(columns={"id": "game_version_id", name_column: "name"})

    return data_df

character_df = combine_dfs(character_df, game_version_df, "Character", "Game")

character_df

                        name  game_version_id
0                      Mario               10
1                      Luigi               10
2                      Peach               10
3                      Daisy               10
4                   Rosalina               10
..                       ...              ...
198      Explorer Baby Daisy               11
199    Touring Baby Rosalina               11
200  Pro Racer Baby Rosalina               11
201     Sailor Baby Rosalina               11
202   Explorer Baby Rosalina               11

[203 rows x 2 columns]

In [ ]:
character_df.to_sql(
    name='character', 
    con=engine, 
    method='multi',
    if_exists='append',
    index=False
)

203

## Vehicles

In [25]:
body_df = pd.read_csv(wd / 'data' / 'vehicles.csv')
glider_df = pd.read_csv(wd / 'data' / 'gliders.csv')
wheel_df = pd.read_csv(wd / 'data' / 'wheels.csv')
game_version_df = pd.read_csv(wd / 'data' / 'game_version.csv')

body_df = combine_dfs(body_df, game_version_df, "vehicle_name", "game")
body_df

                 name  game_version_id
0            B-Dasher               10
1        Master Cycle               10
2     300 SL Roadster               10
3   Master Cycle Zero               10
4            Landship               10
..                ...              ...
70        R.O.B.H.O.G               11
71       Rally Romper               11
72         Rallygator               11
73      Standard Bike               11
74         Li'l Dumpy               11

[75 rows x 2 columns]

In [26]:
body_df.to_sql(
    name='vehicle',
    con=engine,
    if_exists='append',
    index=False
)

75

In [31]:
glider_df.to_sql(
    name='glider',
    con=engine,
    if_exists='append',
    index=False
)

wheel_df.to_sql(
    name='wheel',
    con=engine,
    if_exists='append',
    index=False
)

22

## Tracks

In [34]:
track_df = pd.read_csv(wd / 'data' / 'tracks.csv')
game_version_df = pd.read_csv(wd / 'data' / 'game_version.csv')

track_df = track_df.rename(columns={"name": "track_name"})

track_df = combine_dfs(track_df, game_version_df, 'track_name', 'game_version')

track_df

                    name  game_version_id
0       Excitebike Arena               10
1           Electrodrome               10
2             Water Park               10
3            Toad Harbor               10
4    SNES Donut Plains 3               10
..                   ...              ...
121        Starview Peak               11
122       Toad's Factory               11
123        Wario Stadium               11
124      Wario's Galleon               11
125   Whistlestop Summit               11

[126 rows x 2 columns]

In [35]:
track_df.to_sql(
    name='track',
    con=engine,
    if_exists='append',
    index=False
)

126

## Misc. Data

There is some data which it's just easier to do by hand

Data:
* CC's
* CPU difficulty
* Course selection method
* Item rules
* Points (done in Excel)

In [ ]:
cc_df = pd.DataFrame(
    data={"name": ['50cc', '100cc', '150cc', 'Mirror', '200cc', '50cc', '100cc', '150cc', 'Mirror'],
          "game_version_id": [10, 10, 10, 10, 10, 11, 11, 11, 11]}
)

cpu_difficulty_df = pd.DataFrame(
    data={"name": ['Easy', 'Medium', 'Hard', 'Easy', 'Medium', 'Hard'],
          "game_version_id": [10, 10, 10, 11, 11, 11]}
)

course_select_df = pd.DataFrame(
    data={
        "name": ['Choose', 'Random', 'In Order', 'Open', 'Random', 'Connected'],
        "game_version_id": [10, 10, 10, 11, 11, 11]
    }
)

item_rules_df = pd.DataFrame(
    data={
        "name": ['Custom Items', 'Normal Items', 'Shells Only', 'Bananas Only', 'Mushrooms Only', 'Bob-ombs Only', 'No Items', 'No Items or Coins', 'Frantic Items', 
                 'Custom Items', 'Normal', 'Mushrooms Only', 'Frantic'],
        "game_version_id": [10, 10, 10, 10, 10, 10, 10, 10, 10,
                            11, 11, 11, 11]
    }
)

points_df = pd.read_csv(wd / 'data' / 'points.csv')

    position  game_version_id  points
0          1               10      15
1          2               10      12
2          3               10      10
3          4               10       9
4          5               10       8
5          6               10       7
6          7               10       6
7          8               10       5
8          9               10       4
9         10               10       3
10        11               10       2
11        12               10       1
12         1               11      15
13         2               11      12
14         3               11      10
15         4               11       9
16         5               11       9
17         6               11       8
18         7               11       8
19         8               11       7
20         9               11       7
21        10               11       6
22        11               11       6
23        12               11       6
24        13               11       5
25        14               11       5
26        15               11       5
27        16               11       4
28        17               11       4
29        18               11       4
30        19               11       3
31        20               11       3
32        21               11       3
33        22               11       2
34        23               11       2
35        24               11       1

In [ ]:
points_df.to_sql(
    name='position',
    con=engine,
    if_exists='append',
    index=False
)

cc_df.to_sql(
    name='engine_class',
    con=engine,
    if_exists='append',
    index=False
)

cpu_difficulty_df.to_sql(
    name='cpu_difficulty',
    con=engine,
    if_exists='append',
    index=False
)

course_select_df.to_sql(
    name='course_selection',
    con=engine,
    if_exists='append',
    index=False
)

item_rules_df.to_sql(
    name='item_rule',
    con=engine,
    if_exists='append',
    index=False
)

13