# Mario Kart Tracker v2: Track Name Correction

In the initial upload, some track names ended up with the American name. Since we want the British name, they need to be updated in the database.

But, we also want to preserve entries that have already been entered, so we don't want to delete and re-insert, meaning that they need to be updated.

Process:
* Get track names from database
* Match them to the CSV containing the new names
* Update database with new names

In [4]:
import pandas as pd
from pathlib import Path
import psycopg2
from sqlalchemy import create_engine

In [5]:
wd = Path()
conn = psycopg2.connect(database="mk_tracker",
                        user="postgres",
                        password="postgres",
                        host="localhost",
                        port=5432)

conn.autocommit = False
cursor = conn.cursor()

In [6]:
engine = create_engine('postgresql://postgres:postgres@localhost:5432/mk_tracker')

In [12]:
new_track_names = pd.read_csv(wd / "data" / "new_mk8_tracks.csv")

new_track_names.head()

             american             british             db_name
0  Mario Kart Stadium  Mario Kart Stadium  Mario Kart Stadium
1          Water Park          Water Park          Water Park
2  Sweet Sweet Canyon  Sweet Sweet Canyon  Sweet Sweet Canyon
3        Thwomp Ruins        Thwomp Ruins        Thwomp Ruins
4       Mario Circuit       Mario Circuit       Mario Circuit

Step 1: Get the old names

In [7]:
read_sql = '''
SELECT *
FROM "track"
WHERE "game_version_id" = (SELECT "game_version_id" FROM "game_version" WHERE "name" = 'Mario Kart 8 Deluxe')
'''

cursor.execute(read_sql)
old_tracks_data = cursor.fetchall()

old_track_names = pd.DataFrame(old_tracks_data, columns=[desc[0] for desc in cursor.description])

old_track_names

    track_id                        name  game_version_id
0          1            Excitebike Arena               10
1          2                Electrodrome               10
2          3                  Water Park               10
3          4                 Toad Harbor               10
4          5         SNES Donut Plains 3               10
..       ...                         ...              ...
91        92          Piranha Plant Cove               10
92        93         Madrid Drive (Tour)               10
93        94  Rosalina's Ice World (3DS)               10
94        95      Bowser Castle 3 (SNES)               10
95        96          Rainbow Road (Wii)               10

[96 rows x 3 columns]

Step 2: Match the names

In [24]:
# This won't match old names which have the "<track name> (<console>)" pattern
american_join_df = old_track_names.merge(
    new_track_names, 
    how="inner", 
    left_on="name", 
    right_on="american"
)
db_join_df = old_track_names.merge(
    new_track_names, 
    how="inner", 
    left_on="name", 
    right_on="db_name"
)

joined_df = pd.concat([american_join_df, db_join_df], axis=0)

joined_df = joined_df.drop_duplicates()

joined_df

,track_id,name,game_version_id,american,british,db_name
0,1,Excitebike Arena,10,Excitebike Arena,Excitebike Arena,Excitebike Arena
1,2,Electrodrome,10,Electrodrome,Electrodrome,Electrodrome
2,3,Water Park,10,Water Park,Water Park,Water Park
3,4,Toad Harbor,10,Toad Harbor,Toad Harbour,Toad Harbour
4,5,SNES Donut Plains 3,10,SNES Donut Plains 3,SNES Donut Plains 3,Donut Plains 3 (SNES)
...,...,...,...,...,...,...
62,91,Daisy Circuit (Wii),10,Wii Daisy Circuit,Wii Daisy Circuit,Daisy Circuit (Wii)
64,93,Madrid Drive (Tour),10,Tour Madrid Drive,Tour Madrid Drive,Madrid Drive (Tour)
65,94,Rosalina's Ice World (3DS),10,3DS Rosalina's Ice World,3DS Rosalina's Ice World,Rosalina's Ice World (3DS)
66,95,Bowser Castle 3 (SNES),10,SNES Bowser Castle 3,SNES Bowser Castle 3,Bowser Castle 3 (SNES)
67,96,Rainbow Road (Wii),10,Wii Rainbow Road,Wii Rainbow Road,Rainbow Road (Wii)

In [30]:
unmatched_old_names = old_track_names[~old_track_names["track_id"].isin(joined_df["track_id"])]

unmatched_old_names

    track_id                      name  game_version_id
66        67  Rock Rock Mountain (3DS)               10
74        75           DK Summit (Wii)               10
75        76            Yoshi’s Island               10

In [26]:
unmatched_new_names = new_track_names[~new_track_names["db_name"].isin(joined_df["db_name"])]
unmatched_new_names

,american,british,db_name
66,3DS Rock Rock Mountain,3DS Alpine Pass,Alpine Pass (3DS)
74,Wii DK Summit,Wii DK's Snowboard Cross,DK's Snowboard Cross (Wii)
75,Yoshi's Island,Yoshi's Island,Yoshi's Island

There are a few that didn't get matched - because of the format issue, and one because of a weird punctuation thing. 

So we'll fix this up and then we can join them

In [35]:
consoles = ["SNES", "N64", "GCN", "GBA", "3DS", "DS", "Wii", "3DS", "Tour"]

def fix_console(track_name: str, consoles: list):
    new_name = track_name
    for console_name in consoles:
        if console_name in new_name:
            # Format the name
            new_name = new_name.replace(console_name, "").strip() + f" ({console_name})"

            break

    return new_name

unmatched_new_names["american_formatted"] = unmatched_new_names["american"].apply(lambda name: fix_console(name, consoles))

unmatched_old_names["name"] = unmatched_old_names["name"].str.replace("’", "'")

unmatched_fixed = unmatched_old_names.merge(
    unmatched_new_names, 
    how="inner", 
    left_on="name", 
    right_on="american_formatted"
)

unmatched_fixed = unmatched_fixed.drop(columns=["american_formatted"])
unmatched_fixed

,track_id,name,game_version_id,american,british,db_name
0,67,Rock Rock Mountain (3DS),10,3DS Rock Rock Mountain,3DS Alpine Pass,Alpine Pass (3DS)
1,75,DK Summit (Wii),10,Wii DK Summit,Wii DK's Snowboard Cross,DK's Snowboard Cross (Wii)
2,76,Yoshi's Island,10,Yoshi's Island,Yoshi's Island,Yoshi's Island

In [36]:
all_names_df = pd.concat([joined_df, unmatched_fixed], axis=0)
all_names_df

,track_id,name,game_version_id,american,british,db_name
0,1,Excitebike Arena,10,Excitebike Arena,Excitebike Arena,Excitebike Arena
1,2,Electrodrome,10,Electrodrome,Electrodrome,Electrodrome
2,3,Water Park,10,Water Park,Water Park,Water Park
3,4,Toad Harbor,10,Toad Harbor,Toad Harbour,Toad Harbour
4,5,SNES Donut Plains 3,10,SNES Donut Plains 3,SNES Donut Plains 3,Donut Plains 3 (SNES)
...,...,...,...,...,...,...
66,95,Bowser Castle 3 (SNES),10,SNES Bowser Castle 3,SNES Bowser Castle 3,Bowser Castle 3 (SNES)
67,96,Rainbow Road (Wii),10,Wii Rainbow Road,Wii Rainbow Road,Rainbow Road (Wii)
0,67,Rock Rock Mountain (3DS),10,3DS Rock Rock Mountain,3DS Alpine Pass,Alpine Pass (3DS)
1,75,DK Summit (Wii),10,Wii DK Summit,Wii DK's Snowboard Cross,DK's Snowboard Cross (Wii)
2,76,Yoshi's Island,10,Yoshi's Island,Yoshi's Island,Yoshi's Island

Step 3: Update the names in the database

In [40]:
# To keep the number of calls small, let's just use the rows where "name" <> "db_name"
update_df = all_names_df[all_names_df["name"] != all_names_df["db_name"]]

update_df = update_df[["track_id", "name", "db_name"]]

update_df

    track_id                      name                      db_name
3          4               Toad Harbor                 Toad Harbour
4          5       SNES Donut Plains 3        Donut Plains 3 (SNES)
5          6        GCN Dry Dry Desert         Dry Dry Desert (GCN)
6          7            Bone-Dry Dunes               Bone Dry Dunes
7          8          N64 Yoshi Valley           Yoshi Valley (N64)
8          9         GCN Yoshi Circuit          Yoshi Circuit (GCN)
11        12             3DS DK Jungle              DK Jungle (3DS)
12        13          N64 Rainbow Road           Rainbow Road (N64)
13        14           GBA Cheese Land            Cheese Land (GBA)
15        16         GBA Mario Circuit          Mario Circuit (GBA)
22        23          GCN Sherbet Land           Sherbet Land (GCN)
27        28   3DS Piranha Plant Slide  Piranha Plant Pipeway (3DS)
28        29          DS Wario Stadium           Wario Stadium (DS)
30        31       Wii Grumble Volcano        Grumble Volcano (Wii)
33        34           GBA Ribbon Road            Ribbon Road (GBA)
34        35         N64 Royal Raceway          Royal Raceway (N64)
36        37       Wii Moo Moo Meadows        Moo Moo Meadows (Wii)
37        38      DS Cheep Cheep Beach       Cheep Cheep Beach (DS)
38        39       N64 Toad's Turnpike        Toad's Turnpike (N64)
39        40            3DS Music Park        Melody Motorway (3DS)
40        41         SNES Rainbow Road          Rainbow Road (SNES)
42        43             GCN Baby Park              Baby Park (GCN)
43        44       3DS Neo Bowser City             Koopa City (3DS)
44        45        DS Tick-Tock Clock         Tick-Tock Clock (DS)
45        46     Wii Wario's Gold Mine      Wario's Gold Mine (Wii)
0         67  Rock Rock Mountain (3DS)            Alpine Pass (3DS)
1         75           DK Summit (Wii)   DK's Snowboard Cross (Wii)

In [44]:
update_sql = '''UPDATE "track"
         SET "name" = %s
         WHERE "track_id" = %s'''

ids = tuple(update_df["track_id"].unique().tolist())

for i, row in update_df.iterrows():
    cursor.execute(update_sql, (row["db_name"], row["track_id"],))

read_sql = f'SELECT * FROM "track" WHERE track_id in {ids}'

cursor.execute(read_sql)

data = cursor.fetchall()

conn.commit()

data

[(4, 'Toad Harbour', 10),
 (5, 'Donut Plains 3 (SNES)', 10),
 (6, 'Dry Dry Desert (GCN)', 10),
 (7, 'Bone Dry Dunes', 10),
 (8, 'Yoshi Valley (N64)', 10),
 (9, 'Yoshi Circuit (GCN)', 10),
 (12, 'DK Jungle (3DS)', 10),
 (13, 'Rainbow Road (N64)', 10),
 (14, 'Cheese Land (GBA)', 10),
 (16, 'Mario Circuit (GBA)', 10),
 (23, 'Sherbet Land (GCN)', 10),
 (28, 'Piranha Plant Pipeway (3DS)', 10),
 (29, 'Wario Stadium (DS)', 10),
 (31, 'Grumble Volcano (Wii)', 10),
 (34, 'Ribbon Road (GBA)', 10),
 (35, 'Royal Raceway (N64)', 10),
 (37, 'Moo Moo Meadows (Wii)', 10),
 (38, 'Cheep Cheep Beach (DS)', 10),
 (39, "Toad's Turnpike (N64)", 10),
 (40, 'Melody Motorway (3DS)', 10),
 (41, 'Rainbow Road (SNES)', 10),
 (43, 'Baby Park (GCN)', 10),
 (44, 'Koopa City (3DS)', 10),
 (45, 'Tick-Tock Clock (DS)', 10),
 (46, "Wario's Gold Mine (Wii)", 10),
 (67, 'Alpine Pass (3DS)', 10),
 (75, "DK's Snowboard Cross (Wii)", 10)]