# Mario Kart Tracker v2: Data Scraping

## Tracks

The aim of this notebook is to scrape the tracks from Mario Kart 8 Deluxe and World and store them in a CSV file

Website(s) to scrape from: 
* Nintendo Website

(We could use the Mario Wiki like for the other notebooks, but let's mix it up a bit)

Required Libraries:
* `Selenium`
* `BeautifulSoup`
* `Pandas`

In [1]:
from bs4 import BeautifulSoup
from selenium import webdriver
import pandas as pd
from pathlib import Path

In [2]:
wd = Path().cwd()
wd = wd.parent

### Mario Kart 8 Deluxe

In [20]:
url = 'https://www.nintendo.com/sg/switch/aabp/course/index.html?srsltid=AfmBOop_vyLUnGFtkTSkk2JqRc9A8QDg9EYDWAlGaJa628hixHt5waPR'

def get_track_html(url):
    driver = webdriver.Firefox()
    driver.get(url)

    # The courses only appear when you scroll down a bit
    driver.execute_script('window.scrollTo(0, document.body.scrollHeight);')

    track_html = driver.page_source

    driver.quit()

    return track_html


standard_html = get_track_html(url)
print(standard_html)

<html data-nsuid="70010000000153" lang="en-SG" data-device="desktop" data-browser="other" data-inframe="0" data-win_tablet="0" class="loader-type-default no-touchevents is-ncommon-ghdr-ua-win" style=""><head>
  <meta charset="UTF-8">
  <!-- Google Tag Manager -->
  <script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/destination?id=AW-10784433429&amp;cx=c&amp;gtm=4e65j1"></script><script src="https://connect.facebook.net/signals/config/4631496183582944?v=2.9.324&amp;r=stable&amp;domain=www.nintendo.com&amp;hme=af8aa31887db259becaf70277daef60bd8bc35c2df82c2acd4258de27ecac4b5&amp;ex_m=104%2C207%2C155%2C22%2C72%2C73%2C146%2C68%2C67%2C11%2C164%2C90%2C16%2C138%2C127%2C39%2C75%2C78%2C134%2C160%2C166%2C8%2C4%2C5%2C7%2C6%2C3%2C91%2C101%2C167%2C172%2C221%2C62%2C188%2C189%2C55%2C279%2C30%2C74%2C233%2C232%2C231%2C23%2C33%2C103%2C61%2C10%2C63%2C97%2C98%2C99%2C105%2C130%2C31%2C29%2C132%2C133%2C129%2C128%2C156%2C76%2C159%2C157%2C158%2C50%2C60%2C123%2C15%2C163%2C45%2C266%2C267%2C265%2C26%2C27%2C28%2C48%2C147%2C77%2C112%2C18%2C20%2C44%2C40%2C42%2C41%2C83%2C92%2C96%2C110%2C145%2C148%2C46%2C111%2C24%2C21%2C119%2C69%2C36%2C150%2C149%2C151%2C142%2C140%2C25%2C35%2C59%2C109%2C162%2C70%2C17%2C153%2C114%2C81%2C66%2C19%2C85%2C86%2C116%2C84%2C136%2C135%2C139%2C161%2C34%2C281%2C297%2C214%2C203%2C204%2C202%2C300%2C291%2C52%2C215%2C107%2C131%2C80%2C121%2C54%2C47%2C49%2C113%2C120%2C126%2C125%2C58%2C64%2C152%2C115%2C37%2C32%2C53%2C56%2C100%2C165%2C1%2C124%2C14%2C122%2C12%2C2%2C57%2C93%2C65%2C118%2C89%2C88%2C168%2C169%2C94%2C95%2C9%2C102%2C51%2C143%2C87%2C79%2C71%2C117%2C106%2C43%2C144%2C0%2C82%2C137%2C141%2C154%2C38%2C108%2C13%2C170" async=""></script><script async="" src="https://connect.facebook.net/en_US/fbevents.js"></script><script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/js?id=G-Q2XMW0E3ZW&amp;cx=c&amp;gtm=4e65j1"></script><script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-58TNBSW"></script><script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});
  var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';
  j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer','GTM-58TNBSW');</script>
  <!-- End Google Tag Manager -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=1240">
  <title>Courses | Mario Kart 8 Deluxe | Nintendo Switch | Nintendo</title>
  <meta name="description" content="This is the &quot;Courses&quot; page of the Nintendo Switch game &quot;Mario Kart 8 Deluxe&quot;.&quot;">
  <meta name="keywords" content="Mario Kart 8 Deluxe, Mario Kart, game, Nintendo Switch, Nintendo, Switch">

  <!-- ogp -->
  <meta property="og:site_name" content="Nintendo Official Website (Singapore)">
  <meta property="og:title" content="Mario Kart 8 Deluxe | Nintendo Switch | Nintendo">
  <meta property="og:description" content="This is the official homepage of &quot;Mario Kart 8 Deluxe&quot; for Nintendo Switch, released on 28 April 2017. Play anytime, anywhere! Races, battles – everything is deluxe! Mario Kart 8 Deluxe offers you all-new characters, courses and vehicles! And a Battle mode to get stuck into at home or on the road!">
  <meta property="og:url" content="https://www.nintendo.com/sg/switch/aabp/index.html">
  <meta property="og:image" content="https://www.nintendo.com/sg/switch/aabp/sns.png">
  <meta property="og:type" content="article">
  <meta property="og:locale" content="en-SG">
  <!-- /ogp -->

  <meta property="twitter:card" content="summary_large_image">
  <meta property="twitter:site" content="@Nintendo">
  <meta property="twitter:creator" content="@Nintendo">
  <meta property="twitter:title" content="Mario Kart 8 Deluxe | Nintendo Switch | Nintendo">
  <meta property="twitter:description" content="This is the official homepage of &quot;Mario Kart 8 Deluxe&quot; for Nintendo Switch, released on 28 April 2017. Play anytime, anywhere! Races, battles – everything is deluxe! Mario Kart 8 Deluxe offers you all-new characters, courses and vehicles! And a Battle mode to get stuck into at home or on the road!">
  <meta property="twitter:image:src" content="https://www.nintendo.com/sg/switch/aabp/sns.png">

  <!--&#91;if IE 6&#93;>
     <link rel="stylesheet" type="text/css" href="../assets/css/ie.css" />
  <!&#91;endif&#93;-->
  <!--&#91;if IE 7&#93;>
     <link rel="stylesheet" type="text/css" href="../assets/css/ie.css" />
  <!&#91;endif&#93;-->
  <!--&#91;if IE 8&#93;>
     <link rel="stylesheet" type="text/css" href="../assets/css/ie.css" />
  <!&#91;endif&#93;-->
  <!--&#91;if gte IE 8&#93;>
     <link rel="stylesheet" type="text/css" href="../assets/css/ie.css" />
  <!&#91;endif&#93;-->

  <link rel="alternate" media="only screen and(max-width:640px)" href="https://www.nintendo.com/sg/switch/aabp/sp/course/index.html">
  <link rel="canonical" href="https://www.nintendo.com/sg/switch/aabp/course/index.html">
  <link rel="stylesheet" href="../assets/css/loading.css">
  <link rel="stylesheet" href="../assets/css/swiper.min.css">
  <link rel="stylesheet" href="../assets/css/menu.css">
  <link rel="stylesheet" href="../assets/css/style.css">

  <script src="../assets/js/nt_redirect.js"></script>
  <script src="../assets/js/nt_redirect_config.js"></script>

  <script src="../assets/js/libs/jquery-2.1.4.js"></script>
  <script src="../assets/js/libs/jquery-1.11.1.js"></script>
  <script type="text/javascript">
    var $111 = $.noConflict(true);
  </script>
  <script src="../assets/js/libs/jquery.bxslider.min.js" defer=""></script>
  <script src="../assets/js/libs/swiper.jquery.min.js" defer=""></script>
  <script src="../assets/js/function.js" defer=""></script>
  <script src="../assets/js/mv.js" defer=""></script>
  <script src="../assets/js/overlay.js" defer=""></script>
  <script src="../assets/js/battle.js" defer=""></script>
  <script src="../assets/js/libs/jquery.lazyload.js" defer=""></script>
  <script src="../assets/js/init.js" defer=""></script>

  <!-- ncommon global header start -->
  <link rel="stylesheet" href="../../../../common-a/v1/css/gheader.css">
  <script src="../../../../common-a/v1/js/gheader.js"></script><script src="/common-a/v3/js/svgpack.js" async=""></script><link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:,400,700,900"><script src="../../../../common-a/v3/js/svgpack.js" async=""></script>
  <!-- ncommon global header end -->

<!-- icon -->
  <link rel="icon" href="/common-a/img/favicon.ico">
  <!-- <link rel="apple-touch-icon" href="/common-a/img/apple-touch-icon-precomposed.png"> -->
  <!-- //icon -->

<script type="text/javascript" async="" src="https://googleads.g.doubleclick.net/pagead/viewthroughconversion/10784433429/?random=1779351595701&amp;cv=11&amp;fst=1779351595701&amp;bg=ffffff&amp;guid=ON&amp;async=1&amp;gtm=45be65j1z8849114039za20gzb849114039zd849114039xea&amp;gcd=13l3l3l3l1l1&amp;dma=0&amp;tag_exp=0~115938465~115938468~118128923~118228214&amp;u_w=1440&amp;u_h=900&amp;url=https%3A%2F%2Fwww.nintendo.com%2Fsg%2Fswitch%2Faabp%2Fcourse%2Findex.html%3Fsrsltid%3DAfmBOop_vyLUnGFtkTSkk2JqRc9A8QDg9EYDWAlGaJa628hixHt5waPR&amp;rcb=15&amp;frm=0&amp;tiba=Courses%20%7C%20Mario%20Kart%208%20Deluxe%20%7C%20Nintendo%20Switch%20%7C%20Nintendo&amp;hn=www.googleadservices.com&amp;npa=0&amp;pscdl=noapi&amp;auid=1946211475.1779351595&amp;_tu=CA&amp;rfmt=3&amp;fmt=4"></script></head>

<body>
  <script>
    //LazyLoad
    $111(function () {
      $('img.lazy').lazyload();
    });
    $111(function () {
      $("img.below-the-fold").lazyload({
        event: "sporty"
      });
    });
    $111(window).bind("load", function () {
      var timeout = setTimeout(function () {
        $("img").trigger("sporty")
      }, 20);
    });
  </script>

  <!-- Google Tag Manager (noscript) -->
  <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-58TNBSW" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
  <!-- End Google Tag Manager (noscript) -->
  <div id="ncommon-ghdr-header" class="show is-new-ghdr nc3-c-gheader is-visible is-show">
  <!-- THIRD-PARTY SOFTWARE NOTICES AND INFORMATION: see /sg/ThirdPartyNotices.txt -->
  <div class="nc3-js-megaDrop is-moduleready" data-disabled="0" data-inited-megadrop="1">
    <div class="nc3-js-megaDrop__bg"></div>

    <div class="nc3-c-gheader-dfHeader" data-domain="www.nintendo.com" data-level1="switch" data-level2="aabp">
      <div class="nc3-l-innerWidth--tabSp">
        <div class="nc3-c-gheader-dfHeader__logo"><a href="/sg/index.html"><svg><use xlink:href="#nc3-svgpack-logo-nintendo"></use></svg>Nintendo</a></div>
        <ul class="nc3-c-gheader-dfHeader__sub">

  <li class="nc3-c-gheader-dfHeader__subItem nc3-c-gheader-dfHeader__subItem--search">
    <a href="#" class="nc3-js-megaDrop__buttonHover" data-group="megadrop_sub" data-key="search"><span class="nc3-c-gheader-dfHeader__icon"><svg><use xlink:href="#nc3-svgpack-icon-search"></use></svg></span><span class="nc3-c-gheader-dfHeader__label">Search</span></a>
  </li>
        </ul>
      </div>
    </div>


    <div class="nc3-c-gheader-dropArea nc3-c-gheader-dropArea--sub nc3-js-megaDrop__content" data-group="megadrop_sub" data-njs-fixed="1">
      <div class="nc3-js-megaDrop__contentClip">
        <div class="nc3-c-gheader-dropArea__outer nc3-js-megaDrop__contentOuter">
          <div class="nc3-c-gheader-dropArea__inner nc3-js-megaDrop__contentInner">

          <div class="nc3-js-megaDrop__contentItem">
            <div class="nc3-c-gheader-dropArea__body">
              <div class="nc3-l-innerWidth--pcTab">
                <div id="nc3-c-gheader-searchAreaWrap"><form class="nc3-as-box nc3-js-searchBox is-moduleready" data-key="ghq" action="" data-inited-searchbox="1">
    <div class="nc3-c-search nc3-c-search--noFrame">
      <div class="nc3-c-search__text">
        <div class="nc3-c-search__box">
          <svg><use xlink:href="#nc3-svgpack-icon-search"></use></svg>
          <input type="search" placeholder="Enter Keyword(s)" class="nc3-c-search__boxText nc3-js-megadrop__focusable nc3-js-searchBox__text" maxlength="100">
          <div class="nc3-c-search__boxReset nc3-js-searchBox__clear"><i class="nc3-a-icon"><svg><use xlink:href="#nc3-svgpack-icon-searchbox-clear"></use></svg></i></div>
          <button class="nc3-c-search__boxButton"><span>Search</span></button>
        </div>
        <div class="nc3-as-box__drop nc3-c-search__drop">
          <div class="nc3-as-box__dropList nc3-c-search__dropList" data-name="search_main_soft">
            <ul class="nc3-as-box__dropListContainer nc3-c-search__dropListContainer"></ul>
          </div>
          <div class="nc3-as-box__dropList nc3-c-search__dropList" data-name="search_main_page">
            <ul class="nc3-as-box__dropListContainer nc3-c-search__dropListContainer"></ul>
          </div>
        </div>
      </div>
      <div class="nc3-c-search__recommend nc3-js-carouselNav is-on-left is-on-right is-moduleready" data-inited-carouselnav="1">
        <ul class="nc3-c-search__recommendList nc3-js-carouselNav__list" id="nc3-c-search__recommendList">
        </ul>
        <button class="nc3-js-carouselNav__left"><div class="nc3-a-buttonPager nc3-a-buttonPager--mini"><i class="nc3-a-icon"><svg><use xlink:href="#nc3-svgpack-icon-arrow-mini-left"></use></svg></i></div></button>
        <button class="nc3-js-carouselNav__right"><div class="nc3-a-buttonPager nc3-a-buttonPager--mini"><i class="nc3-a-icon"><svg><use xlink:href="#nc3-svgpack-icon-arrow-mini-right"></use></svg></i></div></button>
      </div>
    </div>
  </form></div>
              </div>
            </div>
            <div class="nc3-c-gheader-dropArea__close"><div class="nc3-c-gheader-dropArea__closeButton nc3-js-megaDrop__close"><svg><use xlink:href="#nc3-svgpack-gheader-droparea-icon-close"></use></svg><span>Close</span></div></div>
          </div>

          </div>
        </div>
      </div>
    </div>

  </div>
  </div>

  <!-- Mario Kart 8 Deluxe contents start -->
  <div id="mkWrapper">
    <!-- from load to battle-->
    <div id="mkContainer">

      <!-- コース #course-->
      <section class="section separator wh" id="course" data-color="wh">
        <div class="img_line type_right animate">

          <div class="loop_slide rl" data-type="right_to_left">
            <div class="loopSliderWrap cf" style="width: 5256px; transform: translate(-2628px); transition-duration: 30s;" data-width="2628" data-speed="87.6" data-time="30"><ul class="cf" style="width: 2628px;">
              <li><img src="../assets/images/course/detail/7-1.jpg" alt=""></li>
              <li><img src="../assets/images/course/detail/7-2.jpg" alt=""></li>
              <li><img src="../assets/images/course/detail/7-3.jpg" alt=""></li>
              <li><img src="../assets/images/course/detail/7-4.jpg" alt=""></li>
            </ul><ul class="cf" style="width: 2628px;">
              <li><img src="../assets/images/course/detail/7-1.jpg" alt=""></li>
              <li><img src="../assets/images/course/detail/7-2.jpg" alt=""></li>
              <li><img src="../assets/images/course/detail/7-3.jpg" alt=""></li>
              <li><img src="../assets/images/course/detail/7-4.jpg" alt=""></li>
            </ul></div>
          </div>
        </div>

        <div class="page_switch_logo"><a href="../../../games/switch/index.html"><img src="../assets/images/common/logo_switch.png" alt="Nintendo Switch"></a></div>

        <div class="scene_chara target action">
          <div class="sc1 sc animate"><img src="../assets/images/scene/img_shizue.png" alt=""></div>
        </div>

        <section class="content" id="courseContents">
          <div class="inner">
            <h2><img src="../assets/images/course/title_course.png" alt="The Excitebike Arena, The Legend of Zelda course and more! Never in the series have there been so many courses to race!">
            </h2>
            <div class="label"><img src="../assets/images/course/img_label.png" alt="48 courses"></div>

            <div id="courseList" class="btn_modal">
              <dl class="cup01 target action">
                <dt>Mushroom Cup</dt>
                <dd class="cf">
                  <ul class="cf">
                    <li><a href="javascript:void(0)" data-id="0" data-modal="courseModal"><img class="below-the-fold" data-original="../assets/images/course/thumbnail/1-1.jpg" alt="Mario Kart Stadium" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC"></a></li>
                    <li><a href="javascript:void(0)" data-id="1" data-modal="courseModal"><img class="below-the-fold" data-original="../assets/images/course/thumbnail/1-2.jpg" alt="Water Park" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC"></a></li>
                    <li><a href="javascript:void(0)" data-id="2" data-modal="courseModal"><img class="below-the-fold" data-original="../assets/images/course/thumbnail/1-3.jpg" alt="Sweet Sweet Canyon" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC"></a></li>
                    <li><a href="javascript:void(0)" data-id="3" data-modal="courseModal"><img class="below-the-fold" data-original="../assets/images/course/thumbnail/1-4.jpg" alt="Thwomp Ruins" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC"></a></li>
                  </ul>
                </dd>
              </dl>

              <dl class="cup02 target action">
                <dt>Flower Cup</dt>
                <dd class="cf">
                  <ul class="cf">
                    <li><a href="javascript:void(0)" data-id="4" data-modal="courseModal"><img class="below-the-fold" data-original="../assets/images/course/thumbnail/2-1.jpg" alt="Mario Circuit" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC"></a></li>
                    <li><a href="javascript:void(0)" data-id="5" data-modal="courseModal"><img class="below-the-fold" data-original="../assets/images/course/thumbnail/2-2.jpg" alt="Toad Harbor" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC"></a></li>
                    <li><a href="javascript:void(0)" data-id="6" data-modal="courseModal"><img class="below-the-fold" data-original="../assets/images/course/thumbnail/2-3.jpg" alt="Twisted Mansion" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC"></a></li>
                    <li><a href="javascript:void(0)" data-id="7" data-modal="courseModal"><img class="below-the-fold" data-original="../assets/images/course/thumbnail/2-4.jpg" alt="Shy Guy Falls" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC"></a></li>
                  </ul>
                </dd>
              </dl>

              <dl class="cup03 target action">
                <dt>Star Cup</dt>
                <dd class="cf">
                  <ul class="cf">
                    <li><a href="javascript:void(0)" data-id="8" data-modal="courseModal"><img class="below-the-fold" data-original="../assets/images/course/thumbnail/3-1.jpg" alt="Sunshine Airport" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC"></a></li>
                    <li><a href="javascript:void(0)" data-id="9" data-modal="courseModal"><img class="below-the-fold" data-original="../assets/images/course/thumbnail/3-2.jpg" alt="Dolphin Shoals" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC"></a></li>
                    <li><a href="javascript:void(0)" data-id="10" data-modal="courseModal"><img class="below-the-fold" data-original="../assets/images/course/thumbnail/3-3.jpg" alt="Electrodrome" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC"></a></li>
                    <li><a href="javascript:void(0)" data-id="11" data-modal="courseModal"><img class="below-the-fold" data-original="../assets/images/course/thumbnail/3-4.jpg" alt="Mount Wario" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC"></a></li>
                  </ul>
                </dd>
              </dl>

              <dl class="cup04 target action">
                <dt>Special Cup</dt>
                <dd class="cf">
                  <ul class="cf">

In [15]:
# We're looking for the names, which are helpfully contained within p tags with 
# the class "name"
track_soup = BeautifulSoup(track_html)

name_tags = track_soup.find_all('p', class_ = 'name')

names = [p.text for p in name_tags]

# There should be 48 here (we'll do DLC after)
print(f"{len(names)} course names found")

144 course names found

In [17]:
# Okay, there are some that shouldn't be there

# Remove duplicates
names = list(set(names))
print(f"{len(names)} course names found")

48 course names found

In [21]:
# Let's get the DLC names, too
dlc_url = 'https://mariokart8.nintendo.com/booster-course-pass/'

dlc_html = get_track_html(dlc_url)
print(dlc_html)

<html lang="en" locale="en-us" data-eshop-lang="en" data-eshop-country="us,ca" class="svg cssanimations flexboxlegacy fontface csstransforms supports csstransforms3d csstransitions inlinesvg alps-ua-firefox alps-os-windows"><head><style class="vjs-styles-defaults">
      .video-js {
        width: 300px;
        height: 150px;
      }

      .vjs-fluid {
        padding-top: 56.25%
      }
    </style>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Mario Kart 8 Deluxe — Booster Course Pass for the Mario Kart 8 Deluxe game on the Nintendo Switch™ system — Official Site</title>

  <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=1">


    <meta property="og:title" content="Mario Kart 8 Deluxe — Booster Course Pass for the Mario Kart 8 Deluxe game on the Nintendo Switch™ system — Official Site">
    <meta property="og:description" content="Add a total of 48 more courses and 8 additional characters to the Mario Kart 8 Deluxe game as paid DLC.">
    <meta property="og:image" content="https://mariokart8.nintendo.com/assets/img/share-fb.jpg">
    <meta property="og:url" content="https://mariokart8.nintendo.com/booster-course-pass">
    <meta property="og:type" content="website">
    <meta property="fb:app_id" content="775678255785283">
    <meta name="google-site-verification" content="lcC2m3GxLFXRpw4s4cKbn8Q6jDs8zHPXp9CC1xHn70c">
    <meta name="msvalidate.01" content="CD9A42A71E67EDC970DE6AD9919B5D79">
    <meta name="description" content="Add a total of 48 more courses and 8 additional characters to the Mario Kart 8 Deluxe game as paid DLC.">
    <meta name="twitter:title" content="Mario Kart™ 8 Deluxe for Nintendo Switch™ – Official Site">
    <meta name="twitter:description" content="Add a total of 48 more courses and 8 additional characters to the Mario Kart 8 Deluxe game as paid DLC. https://mariokart8.nintendo.com/booster-course-pass">
    <meta name="twitter:image" content="https://mariokart8.nintendo.com/assets/img/share-tw.jpg">

    <link rel="shortcut icon" type="image/x-icon" href="../assets/img/global/favicon.ico">
    <link rel="icon" type="image/x-icon" href="../assets/img/global/favicon.ico">
    <link rel="canonical" href="https://mariokart8.nintendo.com">

    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700,900" rel="stylesheet">

    <link rel="stylesheet" href="//media.nintendo.com/share/nclood/stable/en-us/bundles/microsite.css">




    <link href="../assets/css/main.css" rel="stylesheet">
    <link href="../assets/css/mod-gallery.css" rel="stylesheet">
    <link href="../assets/css/modal.css" rel="stylesheet">



    <link href="../assets/css/booster.css" rel="stylesheet">

    <script async="" src="https://s.pinimg.com/ct/lib/main.948ee93e.js"></script><script async="" src="https://static.ads-twitter.com/uwt.js"></script><script type="text/javascript" async="" src="https://s.pinimg.com/ct/core.js"></script><script type="text/javascript" async="" src="https://bat.bing.com/bat.js"></script><script src="https://connect.facebook.net/signals/config/635430006918397?v=2.9.324&amp;r=stable&amp;domain=mariokart8.nintendo.com&amp;hme=af8aa31887db259becaf70277daef60bd8bc35c2df82c2acd4258de27ecac4b5&amp;ex_m=104%2C207%2C155%2C22%2C72%2C73%2C146%2C68%2C67%2C11%2C164%2C90%2C16%2C138%2C127%2C39%2C75%2C78%2C134%2C160%2C166%2C8%2C4%2C5%2C7%2C6%2C3%2C91%2C101%2C167%2C172%2C221%2C62%2C188%2C189%2C55%2C279%2C30%2C74%2C233%2C232%2C231%2C23%2C33%2C103%2C61%2C10%2C63%2C97%2C98%2C99%2C105%2C130%2C31%2C29%2C132%2C133%2C129%2C128%2C156%2C76%2C159%2C157%2C158%2C50%2C60%2C123%2C15%2C163%2C45%2C266%2C267%2C265%2C26%2C27%2C28%2C48%2C147%2C77%2C112%2C18%2C20%2C44%2C40%2C42%2C41%2C83%2C92%2C96%2C110%2C145%2C148%2C46%2C111%2C24%2C21%2C119%2C69%2C36%2C150%2C149%2C151%2C142%2C140%2C25%2C35%2C59%2C109%2C162%2C70%2C17%2C153%2C114%2C81%2C66%2C19%2C85%2C86%2C116%2C84%2C136%2C135%2C139%2C161%2C34%2C281%2C297%2C214%2C203%2C204%2C202%2C300%2C291%2C52%2C215%2C107%2C131%2C80%2C121%2C54%2C47%2C49%2C113%2C120%2C126%2C125%2C58%2C64%2C152%2C115%2C37%2C32%2C53%2C56%2C100%2C165%2C1%2C124%2C14%2C122%2C12%2C2%2C57%2C93%2C65%2C118%2C89%2C88%2C168%2C169%2C94%2C95%2C9%2C102%2C51%2C143%2C87%2C79%2C71%2C117%2C106%2C43%2C144%2C0%2C82%2C137%2C141%2C154%2C38%2C108%2C13%2C170" async=""></script><script type="text/javascript" async="" src="https://connect.facebook.net/en_US/fbevents.js"></script><script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/js?id=DC-9264223&amp;cx=c&amp;gtm=4e65j1"></script><script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/js?id=AW-760306877&amp;cx=c&amp;gtm=4e65j1"></script><script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/js?id=AW-718328300&amp;cx=c&amp;gtm=4e65j1"></script><script type="text/javascript" async="" src="https://www.googletagmanager.com/gtag/js?id=G-F6ERC4HMNZ&amp;cx=c&amp;gtm=4e65j1"></script><script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-WS6V89B"></script><script>
        document.addEventListener('DOMContentLoaded', function() {
          nclood.CookieConsent('eec62c8e-a036-4d3b-8eaa-abf640c9580f');
        }, false);
      </script>


In [26]:
dlc_soup = BeautifulSoup(dlc_html)

dlc_name_spans = dlc_soup.find_all('span', class_ = 'plaque-image__plaque')
dlc_console_spans = dlc_soup.find_all('span', class_ = 'plaque-image__console')

dlc_names = []

for idx in range(0, len(dlc_name_spans)):
    name = dlc_name_spans[idx].text
    console = dlc_console_spans[idx].text

    if console:
        course_name = f"{name} ({console})"
    else:
        course_name = name

    dlc_names.append(course_name)

print(f"{len(dlc_names)} DLC cources found")

48 DLC cources found

In [27]:
# We've now found all the names for MK8!
# Just need to put them into their own dataframe

names.extend(dlc_names)

track_df = pd.DataFrame(names, columns=['name'])

track_df

                          name
0             Excitebike Arena
1                 Electrodrome
2                   Water Park
3                  Toad Harbor
4          SNES Donut Plains 3
..                         ...
91          Piranha Plant Cove
92         Madrid Drive (Tour)
93  Rosalina's Ice World (3DS)
94      Bowser Castle 3 (SNES)
95          Rainbow Road (Wii)

[96 rows x 1 columns]

### Mario Kart World

Now we can move onto MK World - hopefully it's as easy as 8

In [30]:
url = 'https://www.ign.com/wikis/mario-kart-world/Track_List'

driver = webdriver.Firefox()
driver.get(url)

world_html = driver.page_source

driver.quit()

print(world_html)

<html lang="en" data-build-id="KU_FytxpY_ELBBZM5olQ_" data-kraken-env="production" data-release="v0.97.49" data-theme="dark" color-scheme="light" style="color-scheme: dark;"><head prefix="og: http://ogp.me/ns# article: http://ogp.me/ns/article# fb: http://www.facebook.com/2008/fbml"><script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-K7G5DNRH"></script><script src="https://s0.2mdn.net/instream/video/client.js" async="" type="text/javascript"></script><script async="" data-jsonpid="" src="https://cdn-gl.imrworldwide.com/novms/js/2/nlsSDK600.bundle.min.js"></script><script async="" src="https://cdn-gl.imrworldwide.com/conf/config250.js#name=v60Bsdk__1779352521778&amp;ns=NOLBUNDLE"></script><script async="" src="https://sb.scorecardresearch.com/beacon.js"></script><script async="" 0="h" 1="t" 2="t" 3="p" 4="s" 5=":" 6="/" 7="/" 8="b" 9="-" 10="c" 11="o" 12="d" 13="e" 14="." 15="l" 16="i" 17="a" 18="d" 19="m" 20="." 21="c" 22="o" 23="m" 24="/" 25="a" 26="-" 27="0" 28="1" 29="s" 30="i" 31="." 32="m" 33="i" 34="n" 35="." 36="j" 37="s"></script><script async="" src="https://au-script.dotmetrics.net/door.js?d=www.ign.com&amp;t=other"></script><script async="" src="https://securepubads.g.doubleclick.net/tag/js/gpt.js?network-code=5691" referrerpolicy="no-referrer"></script><script async="" src="https://cdn.static.zdbb.net/js/z0WVjCBSEeGLoxIxOQVEwQ.min.js"></script><script async="" src="https://client.aps.amazon-adsystem.com/publisher.js"></script><script async="" id="D4QxaEgV4932fC_gwr4qNIJFm44" src="//cdn.confiant-integrations.net/video/202605191507/wrap.js"></script><script type="text/javascript" async="" src="https://secure-au.imrworldwide.com/v60a.js"></script><script type="text/javascript" async="" src="//static.chartbeat.com/js/chartbeat_video.js"></script><script async="" tag="script" src="https://openads-cdn.adsrvr.org/openadsjs/build/v1.0/ziffdavis/openads.js"></script><script async="" tag="script" src="https://pub.doubleverify.com/dvtag/26327901/DV1293845/pub.js"></script><script async="" tag="script" src="https://cdn.ziffstatic.com/pg/ign.prebid.js"></script><link tag="link" rel="preload" href="https://client.aps.amazon-adsystem.com/publisher.js" as="script"><script id="D4QxaEgV4932fC_gwr4qNIJFm44" async="" src="//cdn.confiant-integrations.net/D4QxaEgV4932fC_gwr4qNIJFm44/video/config.js"></script><script async="" src="//cdn.confiant-integrations.net/gptprebidnative/202605191507/wrap.js"></script><script type="text/javascript" async="" src="https://cdn.confiant-integrations.net/t3dNes-2VKxdhebOtwezHpQAoHM/gpt_and_prebid/config.js"></script><script async="" src="https://config.aps.amazon-adsystem.com/configs/3158"></script><link tag="link" rel="preconnect" href="https://aax.amazon-adsystem.com"><meta charset="utf-8"><title>Track List - Mario Kart World Guide - IGN</title><meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover"><meta name="format-detection" content="telephone=no, date=no, email=no, address=no"><meta name="theme-color" content="#BF1313"><meta name="description" content="There are several brand-new tracks in Mario Kart World, including returning favorites such as Rainbow Road, Mario Circuit, and Bowser&amp;apos;s Castle. This guide"><meta name="robots" content="noodp, noydir, max-image-preview:large"><meta name="bingbot" content="noarchive"><meta property="og:url" content="https://www.ign.com/wikis/mario-kart-world/Track_List"><meta property="og:title" content="Track List - Mario Kart World Guide - IGN"><meta property="og:type" content="website"><meta name="cXenseParse:keywords" content="Mario Kart World,Mario,Mario Kart,Nintendo Switch 2,Action,Racing,Nintendo,Nintendo Entertainment Analysis &amp; Development (EAD),Online Versus Multiplayer,Open-World,Online 24-Player Multiplayer"><meta property="article:published_time" content="2025-06-06T02:24:52Z"><meta property="article:modified_time" content="2025-06-06T09:10:29Z"><meta name="section" content="wiki"><meta property="og:image" content="https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-world/6/6d/Mario_Kart_World_-_Track_Map.png"><meta name="thumbnail" content="https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-world/6/6d/Mario_Kart_World_-_Track_Map.png"><meta property="og:description" content="There are several brand-new tracks in Mario Kart World, including returning favorites such as Rainbow Road, Mario Circuit, and Bowser&amp;apos;s Castle. This guide"><link rel="canonical" href="https://www.ign.com/wikis/mario-kart-world/Track_List"><link rel="alternate" hreflang="x-default" href="https://www.ign.com/wikis/mario-kart-world/Track_List"><link rel="alternate" hreflang="en" href="https://www.ign.com/wikis/mario-kart-world/Track_List"><meta property="al:ios:url" content="ign://ign.com/wikis/mario-kart-world/Track_List"><meta property="al:ios:app_store_id" content="284819997"><meta property="al:ios:app_name" content="IGN: Video Game News, Reviews, Guides"><meta property="al:android:url" content="ign://www.ign.com/wikis/mario-kart-world/Track_List"><meta property="al:android:app_name" content="IGN"><meta property="al:android:package" content="com.mobile.ign"><meta property="al:web:url" content="https://www.ign.com/wikis/mario-kart-world/Track_List"><meta name="twitter:app:name:iphone" content="IGN: Video Game News, Reviews, Guides"><meta name="twitter:app:id:iphone" content="284819997"><meta name="twitter:app:url:iphone" content="ign://www.ign.com/wikis/mario-kart-world/Track_List"><meta name="twitter:app:name:ipad" content="IGN: Video Game News, Reviews, Guides"><meta name="twitter:app:id:ipad" content="284819997"><meta name="twitter:app:url:ipad" content="ign://www.ign.com/wikis/mario-kart-world/Track_List"><meta name="twitter:app:name:googleplay" content="IGN"><meta name="twitter:app:id:googleplay" content="com.mobile.ign"><meta name="twitter:app:url:googleplay" content="ign://www.ign.com/wikis/mario-kart-world/Track_List"><meta name="twitter:card" content="summary"><meta name="twitter:site" content="@IGN"><meta name="twitter:imageUrl" content="https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-world/6/6d/Mario_Kart_World_-_Track_Map.png"><meta name="facebook-domain-verification" content="960w7qsbsscw9stu2hxr2xfaes6cvc"><link rel="preload" as="script" href="https://cdn.ziffstatic.com/jst/zdconsent.js"><link rel="preload" as="script" href="https://cdn.ziffstatic.com/pg/ign.js"><link rel="preload" as="script" href="https://cdn.ziffstatic.com/pg/ign.prebid.js"><link rel="preload" as="script" href="https://securepubads.g.doubleclick.net/tag/js/gpt.js?network-code=5691"><script type="text/javascript">window.zdconsent = window.zdconsent || {'run': [], 'cmd':[], 'analytics':[], 'functional':[], 'social':[] };</script><script type="text/javascript" id="pogo" src="https://cdn.ziffstatic.com/pg/ign.js" async=""></script><link rel="stylesheet" href="https://cdn.ziffstatic.com/pg/ign.css"><link rel="preload" as="script" href="https://imasdk.googleapis.com/js/sdkloader/ima3.js"><script type="text/javascript" id="zdconsent" src="https://cdn.ziffstatic.com/jst/zdconsent.js" fetchpriority="high" async="" suppresshydrationwarning="true"></script><meta name="next-head-count" content="50"><link rel="shortcut icon" type="image/x-icon" href="https://kraken.ignimgs.com/favicon.ico"><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="copyright" content="IGN Entertainment, Inc."><meta name="referrer" content="always"><meta name="cpid" content="5a8bca0b2d985966302b4671c3a001ee"><meta property="og:site_name" content="IGN"><meta property="fb:app_id" content="115982828429116"><meta property="fb:pages" content="59685491632"><link rel="preload" href="https://apps.ign.com/video-player/fonts/Inter.var-subset.woff2" as="font" type="font/woff2" crossorigin="anonymous"><link rel="stylesheet" href="https://cdn.ziffstatic.com/pg/ign.css"><link rel="preload" as="script" href="https://cdn.static.zdbb.net/js/z0WVjCBSEeGLoxIxOQVEwQ.min.js"><link rel="preload" href="https://kraken.ignimgs.com/_next/static/css/031861d27949a874.css" as="style"><link rel="stylesheet" href="https://kraken.ignimgs.com/_next/static/css/031861d27949a874.css" data-n-g=""><link rel="preload" href="https://kraken.ignimgs.com/_next/static/css/cae7d87e7f2b778f.css" as="style"><link rel="stylesheet" href="https://kraken.ignimgs.com/_next/static/css/cae7d87e7f2b778f.css" data-n-p=""><noscript data-n-css=""></noscript><script defer="" nomodule="" src="https://kraken.ignimgs.com/_next/static/chunks/polyfills-42372ed130431b0a.js"></script><script src="https://kraken.ignimgs.com/_next/static/chunks/webpack-df9da0d0f798e826.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/framework-3701f6f516313524.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/main-236d69f8b51ad415.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/pages/_app-66efd1f5ae13cd79.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/c2772f35-cccbad95d623ae8c.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/b21cdbbe-a620c98a98493448.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/5e1d2776-7b5d7ef1b67b99e4.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/8538-fe6a17e7385a1d7a.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/7943-9d40cf1f7fc730eb.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/49-1f32d0413413d31e.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/1234-a2d7189106f98cf9.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/9984-e796268b70abf413.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/3063-a9579f30eb06b8d7.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/6720-439b2183f65626bb.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/2953-874701f7ebef8afd.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/8887-888e594f51ab8214.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/789-f9ed26439fb81b27.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/8351-862a1db5476924b4.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/4896-b54fff799dbf6217.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/361-0a16b9514c430a66.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/7096-dda18889bca9b7a7.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/8448-f8a537062854acbe.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/1540-cdcb1961ad76c51f.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/7725-5784a165e58fd351.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/1578-b6e939652d19ae53.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/8512-dfecd0294580b63c.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/20-b9bf8a3b3138f322.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/4215-d006fa1a59ba0a0a.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/1489-7a34b055d2041a09.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/4603-601c7c8603048430.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/2000-71f56b26a979ff1a.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/4426-8aa0ed46a0b06082.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/7989-5ec620ab0a07f566.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/650-50dc2c8fb49cc6b6.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/2829-9c5209f1d632b8f1.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/8731-63da40e740464b30.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/7224-a65d2562b982be23.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/834-95884608eda5bcfd.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/9378-8e58eeecad30cb57.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/pages/wikis/%5Bslug%5D/%5B...chapter%5D-210095a186401efc.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/KU_FytxpY_ELBBZM5olQ_/_buildManifest.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/KU_FytxpY_ELBBZM5olQ_/_ssgManifest.js" defer=""></script><meta name="sentry-trace" content="1802860d4ea75f6938db0cdc1c3f12d4-fcccb145e21ee03d"><meta name="baggage" content="sentry-environment=production,sentry-release=kraken%3A%3Av0.97.49,sentry-public_key=258f7434a02a42848a43b89281bddba1,sentry-trace_id=1802860d4ea75f6938db0cdc1c3f12d4"><style id="__jsx-2750866048">.ign-icon.jsx-2750866048{position:relative;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;aspect-ratio:1 / 1;width:1em;height:1em;display:inline-block;-webkit-flex-shrink:0;-ms-flex-negative:0;flex-shrink:0;}</style><style id="__jsx-3782449470">.ign-icon.jsx-3782449470{cursor: inherit;
font-size: 1rem;

In [40]:
# This page has the tracks in an unordered list so let's search for that!
world_soup = BeautifulSoup(world_html)

list_items = world_soup.find_all('li')

# We want the ones that do not contain any tags within them
list_items = [tag.text for tag in list_items if len(tag.find_all()) == 0]

# Remove duplicates
list_items = list(set(list_items))

list_items

['DK Pass',
 'Shy Guy Bazaar',
 'Koopa Troopa Beach',
 'Faraway Oasis',
 'Crown City',
 "Wario's Galleon",
 'Mario Bros. Circuit',
 'Great\xa0? Block Ruins',
 'Mario Circuit',
 'Peach Stadium (Version 1)',
 'Choco Mountain',
 'DK Spaceport',
 'Peach Stadium (Version 2)',
 'Sky-High Sundae',
 "Bowser's Castle",
 'Salty Salty Speedway',
 'Acorn Heights',
 'Cheep Cheep Falls',
 'Airship Fortress',
 'Boo Cinema',
 'Dry Bones Burnout',
 'Crown City (Version 2)',
 'Moo Moo Meadows',
 'Rainbow Road',
 'Starview Peak',
 'Dandelion Depths',
 'Desert Hills',
 'Peach Beach',
 'Peach Stadium',
 'Crown City (Version 1)',
 "Toad's Factory",
 'Whistlestop Summit',
 'Wario Galleon',
 'Dino Dino Jungle',
 'Wario Stadium']

We have all the tracks, but there are a couple of funny ones which we need to clean up

In [47]:
world_raw_df = pd.DataFrame(list_items, columns=['name'])

# Seems some had a couple of versions, so remove version numbers
world_raw_df['name'] = world_raw_df['name'].str.replace(pat=r' \(Version \d\)', repl='', regex=True)

world_raw_df = world_raw_df.drop_duplicates().sort_values(by='name')

print(f"{world_raw_df.shape[0]} tracks found")
world_raw_df

31 tracks found

                    name
16         Acorn Heights
18      Airship Fortress
19            Boo Cinema
14       Bowser's Castle
17     Cheep Cheep Falls
10        Choco Mountain
4             Crown City
0                DK Pass
11          DK Spaceport
25      Dandelion Depths
26          Desert Hills
33      Dino Dino Jungle
20     Dry Bones Burnout
3          Faraway Oasis
7    Great ? Block Ruins
2     Koopa Troopa Beach
6    Mario Bros. Circuit
8          Mario Circuit
22       Moo Moo Meadows
27           Peach Beach
9          Peach Stadium
23          Rainbow Road
15  Salty Salty Speedway
1         Shy Guy Bazaar
13       Sky-High Sundae
24         Starview Peak
30        Toad's Factory
32         Wario Galleon
34         Wario Stadium
5        Wario's Galleon
31    Whistlestop Summit

In [51]:
# There's one double-up due to a misspelling. So we'll just delete it
world_clean_df = world_raw_df.copy()

world_clean_df = world_clean_df[world_clean_df['name'] != 'Wario Galleon']

world_clean_df = world_clean_df.reset_index(drop=True)

print(f"{world_clean_df.shape[0]} tracks found")
world_clean_df

30 tracks found

                    name
0          Acorn Heights
1       Airship Fortress
2             Boo Cinema
3        Bowser's Castle
4      Cheep Cheep Falls
5         Choco Mountain
6             Crown City
7                DK Pass
8           DK Spaceport
9       Dandelion Depths
10          Desert Hills
11      Dino Dino Jungle
12     Dry Bones Burnout
13         Faraway Oasis
14   Great ? Block Ruins
15    Koopa Troopa Beach
16   Mario Bros. Circuit
17         Mario Circuit
18       Moo Moo Meadows
19           Peach Beach
20         Peach Stadium
21          Rainbow Road
22  Salty Salty Speedway
23        Shy Guy Bazaar
24       Sky-High Sundae
25         Starview Peak
26        Toad's Factory
27         Wario Stadium
28       Wario's Galleon
29    Whistlestop Summit

### Saving

Now we have all the tracks, so we can save them!

In [53]:
mk8_track_df = track_df.copy()
world_track_df = world_clean_df.copy()

mk8_track_df['game_version'] = 'Mario Kart 8 Deluxe'
world_track_df['game_version'] = 'Mario Kart World'

all_track_df = pd.concat([mk8_track_df, world_track_df], axis=0)

all_track_df

                   name         game_version
0      Excitebike Arena  Mario Kart 8 Deluxe
1          Electrodrome  Mario Kart 8 Deluxe
2            Water Park  Mario Kart 8 Deluxe
3           Toad Harbor  Mario Kart 8 Deluxe
4   SNES Donut Plains 3  Mario Kart 8 Deluxe
..                  ...                  ...
25        Starview Peak     Mario Kart World
26       Toad's Factory     Mario Kart World
27        Wario Stadium     Mario Kart World
28      Wario's Galleon     Mario Kart World
29   Whistlestop Summit     Mario Kart World

[126 rows x 2 columns]

In [54]:
all_track_df.to_csv(wd / 'data' / 'tracks.csv', index=False)