# Mario Kart Tracker v2: Data Scraping

## Tracks

The aim of this notebook is to scrape the tracks from Mario Kart 8 Deluxe and World and store them in a CSV file

Website(s) to scrape from: 
* Mario Wiki

Required Libraries:
* `Selenium`
* `BeautifulSoup`
* `Pandas`

In [2]:
from bs4 import BeautifulSoup
from selenium import webdriver
import pandas as pd
from pathlib import Path
import re

In [3]:
wd = Path().cwd()
wd = wd.parent

### Mario Kart 8 Deluxe

In [4]:
url = 'https://www.mariowiki.com/Mario_Kart_8_Deluxe'

def get_track_html(url):
    driver = webdriver.Firefox()
    driver.get(url)

    # The courses only appear when you scroll down a bit
    driver.execute_script('window.scrollTo(0, document.body.scrollHeight);')

    track_html = driver.page_source

    driver.quit()

    return track_html


standard_html = get_track_html(url)
print(standard_html)

<html class="client-js" lang="en" dir="ltr"><head>
<meta charset="UTF-8">
<title>Mario Kart 8 Deluxe - Super Mario Wiki, the Mario encyclopedia</title>
<script async="" type="text/javascript" src="https://cmp.inmobi.com/tcfv2/cmp2.js?referer=www.mariowiki.com"></script><script async="" type="text/javascript" src="https://cmp.inmobi.com/choice/v0NnnH1M4W081/www.mariowiki.com/choice.js?tag_version=V3"></script><script>document.documentElement.className="client-js";RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"mdy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"f93e1cd4e3d8f26480d5b6e4","wgCSPNonce":false,"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Mario_Kart_8_Deluxe","wgTitle":"Mario Kart 8 Deluxe","wgCurRevisionId":5403865,"wgRevisionId":5403865,"wgArticleId":220017,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles in need of Mario Kart improvement","Pages with audio files","Mario Kart 8 Deluxe","Games","2017 games","2018 games","2019 games","2020 games","Crossover games","Nintendo Switch games","Racing games","Enhanced ports","Games with Nintendo Switch Online","Amiibo-compatible games"],"wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"Mario_Kart_8_Deluxe","wgRelevantArticleId":220017,"wgIsProbablyEditable":false,"wgRelevantPageIsProbablyEditable":false,"wgRestrictionEdit":["autoconfirmed"],"wgRestrictionMove":["autoconfirmed"],"wgMFDisplayWikibaseDescriptions":{"search":false,"nearby":false,"watchlist":false,"tagline":false},"wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":false,"wgPopupsFlags":4};
RLSTATE={"ext.gadget.InterwikiLinkIcons":"ready","ext.gadget.ResponsiveDesktop":"ready","ext.gadget.StaffHighlights":"ready","ext.gadget.ResponsiveStyle":"ready","ext.gadget.MainPageStyle":"ready","ext.gadget.NavboxStyle":"ready","ext.gadget.GlobalStyle":"ready","ext.gadget.TableStyle":"ready","ext.gadget.ProjectPageStyle":"ready","ext.gadget.ShroomStyle":"ready","site.styles":"ready","user.styles":"ready","user":"ready","user.options":"loading","ext.cite.styles":"ready","mediawiki.page.gallery.styles":"ready","ext.tmh.player.styles":"ready","skins.monobook.styles":"ready","jquery.tablesorter.styles":"ready","jquery.makeCollapsible.styles":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","ext.tmh.player","site","mediawiki.page.ready","jquery.tablesorter","jquery.makeCollapsible","mediawiki.toc","skins.monobook.scripts","mmv.head","mmv.bootstrap.autostart","ext.gadget.GlobalScript","ext.gadget.Countdown","ext.gadget.VideoResizer","ext.gadget.ExplainTooltips","ext.gadget.RecentChangesRefresh","ext.gadget.DarkToggle","ext.gadget.Tabber","ext.gadget.ShroomScript","ext.gadget.YouTubePopups","ext.gadget.Awards","ext.popups"];</script>
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.implement("user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});});});</script>
<link rel="stylesheet" href="/load.php?lang=en&amp;modules=ext.cite.styles%7Cext.tmh.player.styles%7Cjquery.makeCollapsible.styles%7Cjquery.tablesorter.styles%7Cmediawiki.page.gallery.styles%7Cskins.monobook.styles&amp;only=styles&amp;skin=monobook">
<script async="" src="/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=monobook"></script>
<style>
.mw-ui-button{background-color:#f8f9fa;color:#202122;display:inline-block;box-sizing:border-box;margin:0;border:1px solid #a2a9b1;border-radius:0.25em;cursor:pointer;vertical-align:middle;font-family:inherit;font-size:1em;font-weight:bold;line-height:1.28571429em;text-align:center; -webkit-appearance:none}.mw-ui-button:not(.mw-ui-icon-element){min-height:32px;min-width:4em;max-width:28.75em;padding:5px 12px}.mw-ui-button:not(:disabled){transition-property:background-color,color,border-color,box-shadow;transition-duration:100ms}.mw-ui-button:not(:disabled):visited{color:#202122}.mw-ui-button:not(:disabled):hover{background-color:#fff;color:#404244;border-color:#a2a9b1}.mw-ui-button:not(:disabled):focus{color:#202122;border-color:#36c;box-shadow:inset 0 0 0 1px #36c,inset 0 0 0 2px #fff;outline-width:0}.mw-ui-button:not(:disabled):focus::-moz-focus-inner{border-color:transparent;padding:0}.mw-ui-button:not(:disabled):active,.mw-ui-button:not(:disabled).is-on{background-color:#c8ccd1;color:#000;border-color:#72777d;box-shadow:none}.mw-ui-button:disabled{background-color:#c8ccd1;color:#fff;border-color:#c8ccd1;cursor:default}.mw-ui-button.mw-ui-icon-element:not(.mw-ui-icon-with-label-desktop){color:transparent !important}.mw-ui-button.mw-ui-icon-element:not(.mw-ui-icon-with-label-desktop) span{display:block;position:absolute !important; clip:rect(1px,1px,1px,1px);width:1px;height:1px;margin:-1px;border:0;padding:0;overflow:hidden}@media all and (max-width:1000px){.mw-ui-button.mw-ui-icon-element.mw-ui-icon-with-label-desktop{color:transparent !important}.mw-ui-button.mw-ui-icon-element span{display:block;position:absolute !important; clip:rect(1px,1px,1px,1px);width:1px;height:1px;margin:-1px;border:0;padding:0;overflow:hidden}}.mw-ui-button.mw-ui-quiet,.mw-ui-button.mw-ui-quiet.mw-ui-progressive,.mw-ui-button.mw-ui-quiet.mw-ui-destructive{background-color:transparent;color:#202122;border-color:transparent;font-weight:bold}.mw-ui-button.mw-ui-quiet:not(.mw-ui-icon-element),.mw-ui-button.mw-ui-quiet.mw-ui-progressive:not(.mw-ui-icon-element),.mw-ui-button.mw-ui-quiet.mw-ui-destructive:not(.mw-ui-icon-element){min-height:32px}input[type='checkbox']:hover + .mw-ui-button.mw-ui-quiet,input[type='checkbox']:hover + .mw-ui-button.mw-ui-quiet.mw-ui-progressive,input[type='checkbox']:hover + .mw-ui-button.mw-ui-quiet.mw-ui-destructive,.mw-ui-button.mw-ui-quiet:hover,.mw-ui-button.mw-ui-quiet.mw-ui-progressive:hover,.mw-ui-button.mw-ui-quiet.mw-ui-destructive:hover{background-color:rgba(0,24,73,0.02745098);color:#202122;border-color:transparent}input[type='checkbox']:focus + .mw-ui-button.mw-ui-quiet,input[type='checkbox']:focus + .mw-ui-button.mw-ui-quiet.mw-ui-progressive,input[type='checkbox']:focus + .mw-ui-button.mw-ui-quiet.mw-ui-destructive,.mw-ui-button.mw-ui-quiet:focus,.mw-ui-button.mw-ui-quiet.mw-ui-progressive:focus,.mw-ui-button.mw-ui-quiet.mw-ui-destructive:focus{color:#202122;border-color:#36c;box-shadow:inset 0 0 0 1px #36c,inset 0 0 0 2px #fff}input[type='checkbox']:active + .mw-ui-button.mw-ui-quiet,input[type='checkbox']:active + .mw-ui-button.mw-ui-quiet.mw-ui-progressive,input[type='checkbox']:active + .mw-ui-button.mw-ui-quiet.mw-ui-destructive,.mw-ui-button.mw-ui-quiet:active,.mw-ui-button.mw-ui-quiet.mw-ui-progressive:active,.mw-ui-button.mw-ui-quiet.mw-ui-destructive:active{background-color:rgba(0,36,73,0.08235294);color:#000;border-color:#72777d;box-shadow:none}.mw-ui-button.mw-ui-quiet:disabled,.mw-ui-button.mw-ui-quiet.mw-ui-progressive:disabled,.mw-ui-button.mw-ui-quiet.mw-ui-destructive:disabled,.mw-ui-button.mw-ui-quiet:disabled:hover,.mw-ui-button.mw-ui-quiet.mw-ui-progressive:disabled:hover,.mw-ui-button.mw-ui-quiet.mw-ui-destructive:disabled:hover,.mw-ui-button.mw-ui-quiet:disabled:active,.mw-ui-button.mw-ui-quiet.mw-ui-progressive:disabled:active,.mw-ui-button.mw-ui-quiet.mw-ui-destructive:disabled:active{background-color:transparent;color:#72777d;border-color:transparent}.mw-ui-button.mw-ui-progressive:not(:disabled){background-color:#36c;color:#fff;border-color:#36c}.mw-ui-button.mw-ui-progressive:not(:disabled):hover{background-color:#447ff5;border-color:#447ff5}.mw-ui-button.mw-ui-progressive:not(:disabled):focus{box-shadow:inset 0 0 0 1px #36c,inset 0 0 0 2px #fff}.mw-ui-button.mw-ui-progressive:not(:disabled):active,.mw-ui-button.mw-ui-progressive:not(:disabled).is-on{background-color:#2a4b8d;border-color:#2a4b8d;box-shadow:none}.mw-ui-button.mw-ui-progressive:disabled{background-color:#c8ccd1;color:#fff;border-color:#c8ccd1}.mw-ui-button.mw-ui-progressive.mw-ui-quiet{color:#36c;background-color:transparent;border-color:transparent}input[type='checkbox']:hover + .mw-ui-button.mw-ui-progressive.mw-ui-quiet,.mw-ui-button.mw-ui-progressive.mw-ui-quiet:hover{background-color:rgba(52,123,255,0.2);border-color:transparent;color:#447ff5}input[type='checkbox']:focus + .mw-ui-button.mw-ui-progressive.mw-ui-quiet,.mw-ui-button.mw-ui-progressive.mw-ui-quiet:focus{color:#36c;border-color:#36c}input[type='checkbox']:active + .mw-ui-button.mw-ui-progressive.mw-ui-quiet,.mw-ui-button.mw-ui-progressive.mw-ui-quiet:active{color:#fff;background-color:#2a4b8d;border-color:#2a4b8d}.mw-ui-button.mw-ui-destructive:not(:disabled){background-color:#d33;color:#fff;border-color:#d33}.mw-ui-button.mw-ui-destructive:not(:disabled):hover{background-color:#ff4242;border-color:#ff4242}.mw-ui-button.mw-ui-destructive:not(:disabled):focus{box-shadow:inset 0 0 0 1px #d33,inset 0 0 0 2px #fff}.mw-ui-button.mw-ui-destructive:not(:disabled):active,.mw-ui-button.mw-ui-destructive:not(:disabled).is-on{background-color:#b32424;border-color:#b32424;box-shadow:none}.mw-ui-button.mw-ui-destructive:disabled{background-color:#c8ccd1;color:#fff;border-color:#c8ccd1}.mw-ui-button.mw-ui-destructive.mw-ui-quiet{color:#d33;background-color:transparent;border-color:transparent}input[type='checkbox']:hover + .mw-ui-button.mw-ui-destructive.mw-ui-quiet,.mw-ui-button.mw-ui-destructive.mw-ui-quiet:hover{background-color:rgba(209,29,19,0.2);border-color:transparent;color:#ff4242}input[type='checkbox']:focus + .mw-ui-button.mw-ui-destructive.mw-ui-quiet,.mw-ui-button.mw-ui-destructive.mw-ui-quiet:focus{color:#d33;border-color:#d33}input[type='checkbox']:active + .mw-ui-button.mw-ui-destructive.mw-ui-quiet,.mw-ui-button.mw-ui-destructive.mw-ui-quiet:active{color:#fff;background-color:#b32424;border-color:#b32424}.mw-ui-button.mw-ui-big{font-size:1.3em}.mw-ui-button.mw-ui-block{display:block;width:100%;margin-left:auto;margin-right:auto}a.mw-ui-button{text-decoration:none}a.mw-ui-button:hover,a.mw-ui-button:focus{text-decoration:none}.mw-ui-button-group > *{min-width:48px;border-radius:0;float:left}.mw-ui-button-group > *:first-child{border-top-left-radius:0.25em;border-bottom-left-radius:0.25em}.mw-ui-button-group > *:not(:first-child){border-left:0}.mw-ui-button-group > *:last-child{border-top-right-radius:0.25em;border-bottom-right-radius:0.25em}.mw-ui-button-group .is-on .button{cursor:default}
.mw-ui-icon{ font-size:initial;position:relative;display:inline-block;box-sizing:content-box !important;width:1.25em;height:1.25em;min-width:1.25em;min-height:1.25em;flex-basis:1.25em;vertical-align:middle;line-height:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap; -moz-appearance:none; -webkit-appearance:none;background-color:transparent;margin:0;padding:0}.mw-ui-icon:not(.mw-ui-button){border:0}.mw-ui-icon:before{content:'';display:block;width:100%;height:100%;min-width:1.25em;min-height:1.25em;background-repeat:no-repeat;background-size:1.25em 1.25em;background-position:center}.mw-ui-icon + span:not(:empty){margin-left:8px} .mw-ui-icon-flush-top{margin-top:-0.75em}.mw-ui-icon-flush-left{margin-left:-0.75em}.mw-ui-icon-flush-right{margin-right:-0.75em}.mw-ui-icon-element{border-radius:0.25em;padding:0.75em;transition:background-color 100ms;color:transparent}.mw-ui-icon-element:focus,.mw-ui-icon-element:active,.mw-ui-icon-element:visited{color:transparent}.mw-ui-icon-element:active{background-color:rgba(0,0,0,0.03)}@media (hover:hover){.mw-ui-icon-element:not(.disabled):hover{background-color:rgba(0,0,0,0.03)}}.mw-ui-icon-small{width:1em;height:1em;min-width:1em;min-height:1em;flex-basis:1em;line-height:1em}.mw-ui-icon-small:before{content:'';display:block;width:100%;height:100%;min-width:1em;min-height:1em;background-repeat:no-repeat;background-size:1em 1em;background-position:center}.mw-ui-icon-small.mw-ui-icon-element{padding:0.5625em}.mw-ui-icon-small.mw-ui-icon-flush-left{margin-left:-0.5625em}.mw-ui-icon-small.mw-ui-icon-flush-right{margin-right:-0.5625em}.mw-ui-icon-small.mw-ui-icon-before:before{min-width:1em;min-height:1em;margin-right:0.5625em}.mw-ui-icon-before{width:auto;max-width:100%}.mw-ui-icon-before:before{display:inline-block; font-size:initial;width:auto;min-width:1.25em;min-height:1.25em;margin-right:8px;vertical-align:middle}.mw-ui-icon-before span{vertical-align:middle}@media all and (min-width:1000px){.mw-ui-icon-with-label-desktop{color:#54595d !important;width:auto;line-height:inherit;flex-basis:auto;font-weight:500 !important}.mw-ui-icon-with-label-desktop:hover,.mw-ui-icon-with-label-desktop:focus,.mw-ui-icon-with-label-desktop:active,.mw-ui-icon-with-label-desktop:visited{color:#54595d;text-decoration:none}.mw-ui-icon-with-label-desktop:before{width:auto;display:inline-block;margin-right:8px;vertical-align:text-bottom}}

In [5]:
# We're looking for tables in the "Courses" section
# They'll be in table rows where the first cell contains "Cup"
track_soup = BeautifulSoup(standard_html)

section_name = track_soup.find("span", {"id": "Courses"})
section_head = section_name.find_parent("h2")
standard_courses_table = section_head.find_next_sibling("table")
standard_course_cells = standard_courses_table.find_all("td")

print(standard_course_cells[:2])

[<td><a class="image" href="/File:MK8_MushroomCup.png"><img alt="Mushroom Cup emblem for Mario Kart 8" data-file-height="122" data-file-width="122" decoding="async" height="60" loading="lazy" src="https://mario.wiki.gallery/images/thumb/1/15/MK8_MushroomCup.png/60px-MK8_MushroomCup.png" srcset="https://mario.wiki.gallery/images/thumb/1/15/MK8_MushroomCup.png/90px-MK8_MushroomCup.png 1.5x, https://mario.wiki.gallery/images/thumb/1/15/MK8_MushroomCup.png/120px-MK8_MushroomCup.png 2x" width="60"/></a><br/><a href="/Mushroom_Cup" title="Mushroom Cup">Mushroom Cup</a>
</td>, <td width="21.25%"><a class="image" href="/File:MK8D_Mario_Kart_Stadium_Course_Icon_Full.png"><img alt="The course icon for Mario Kart Stadium in Mario Kart 8 Deluxe" class="sprite" data-file-height="162" data-file-width="288" decoding="async" height="84" loading="lazy" src="https://mario.wiki.gallery/images/thumb/5/50/MK8D_Mario_Kart_Stadium_Course_Icon_Full.png/150px-MK8D_Mario_Kart_Stadium_Course_Icon_Full.png" srcset="https://mario.wiki.gallery/images/thumb/5/50/MK8D_Mario_Kart_Stadium_Course_Icon_Full.png/225px-MK8D_Mario_Kart_Stadium_Course_Icon_Full.png 1.5x, https://mario.wiki.gallery/images/5/50/MK8D_Mario_Kart_Stadium_Course_Icon_Full.png 2x" width="150"/></a><br/><a href="/Mario_Kart_Stadium" title="Mario Kart Stadium">Mario Kart Stadium</a>
</td>]

In [6]:
from bs4.element import Tag

Some tracks have different names in British English. These are the ones Australia uses, so we need to account for this.

Let's keep both names just to make sure.

In [7]:
def get_british_name(sup: Tag):
    # Get the <a> container, then get the hyperlink id
    id = sup.find("a").get("href")
    # Remove the leading # so we can use it in BeautifulSoup
    id = id.removeprefix("#")
    # Find the element by the id
    note = track_soup.find(id = id)
    # Extract the text from the contained span
    ref_text = note.find("span", class_ = "reference-text")
    ref_text = ref_text.text

    # Extract from between quotation marks
    name = re.findall(r'"(.+)"', ref_text)[0]

    return name

def extract_name(cell: Tag):
    names = {
        "american": None,
        "british": None
    }
    
    # If the name contains the name of the cup, we don't want that, so don't update
    if "Cup" not in cell.text:
        american_name = cell.text.strip("\n")
        
        # Remove any footnote text
        american_name = re.sub(r"\[.\]", "", american_name)
        names["american"] = american_name
        names["british"] = names["american"]

    # We need to check if there is a "sup" element in the cell to check for a footnote
    sup = cell.find_all("sup")

    if sup:
        # If there is, this is the British name, so we need to extract that
        names["british"] = get_british_name(sup[0])

    return names

standard_course_names = [extract_name(cell) for cell in standard_course_cells]

# Remove Nones
standard_course_names = [name for name in standard_course_names if name["american"]]

print(f"{len(standard_course_names)} courses found")

48 courses found

In [8]:
section_name = track_soup.find(id = "Booster_Course_Pass")
section_head = section_name.find_parent("h3")
dlc_courses_table = section_head.find_next("table")
dlc_course_cells = dlc_courses_table.find_all("td")

dlc_names = [extract_name(cell) for cell in dlc_course_cells]

# Remove Nones
dlc_names = [name for name in dlc_names if name]

print(f"{len(dlc_names)} DLC cources found")

48 DLC cources found

In [9]:
# We've now found all the names for MK8!
# Just need to put them into their own dataframe
names = []

names.extend(standard_course_names)
names.extend(dlc_names)

track_df = pd.DataFrame(names)

track_df

                    american                   british
0         Mario Kart Stadium        Mario Kart Stadium
1                 Water Park                Water Park
2         Sweet Sweet Canyon        Sweet Sweet Canyon
3               Thwomp Ruins              Thwomp Ruins
4              Mario Circuit             Mario Circuit
..                       ...                       ...
91        Piranha Plant Cove        Piranha Plant Cove
92         Tour Madrid Drive         Tour Madrid Drive
93  3DS Rosalina's Ice World  3DS Rosalina's Ice World
94      SNES Bowser Castle 3      SNES Bowser Castle 3
95          Wii Rainbow Road          Wii Rainbow Road

[96 rows x 2 columns]

In [ ]:
# The only thing we have to do is fix the console names. We want the names to appear
# in the format "<Track Name> (<Console>)"
# 3DS has to be before DS, since DS is contained within 3DS
consoles = ["SNES", "N64", "GCN", "GBA", "3DS", "DS", "Wii", "3DS", "Tour"]

def fix_console(track_name: str, consoles: list):
    new_name = track_name
    for console_name in consoles:
        if console_name in new_name:
            # Format the name
            new_name = new_name.replace(console_name, "").strip() + f" ({console_name})"

            break

    return new_name

track_df["db_name"] = track_df["british"].apply(lambda name: fix_console(name, consoles))

track_df

,american,british,db_name
0,Mario Kart Stadium,Mario Kart Stadium,Mario Kart Stadium
1,Water Park,Water Park,Water Park
2,Sweet Sweet Canyon,Sweet Sweet Canyon,Sweet Sweet Canyon
3,Thwomp Ruins,Thwomp Ruins,Thwomp Ruins
4,Mario Circuit,Mario Circuit,Mario Circuit
...,...,...,...
91,Piranha Plant Cove,Piranha Plant Cove,Piranha Plant Cove
92,Tour Madrid Drive,Tour Madrid Drive,Madrid Drive (Tour)
93,3DS Rosalina's Ice World,3DS Rosalina's Ice World,Rosalina's Ice World (3DS)
94,SNES Bowser Castle 3,SNES Bowser Castle 3,Bowser Castle 3 (SNES)
95,Wii Rainbow Road,Wii Rainbow Road,Rainbow Road (Wii)

### Mario Kart World

Now we can move onto MK World - hopefully it's as easy as 8

In [30]:
url = 'https://www.ign.com/wikis/mario-kart-world/Track_List'

driver = webdriver.Firefox()
driver.get(url)

world_html = driver.page_source

driver.quit()

print(world_html)

<html lang="en" data-build-id="KU_FytxpY_ELBBZM5olQ_" data-kraken-env="production" data-release="v0.97.49" data-theme="dark" color-scheme="light" style="color-scheme: dark;"><head prefix="og: http://ogp.me/ns# article: http://ogp.me/ns/article# fb: http://www.facebook.com/2008/fbml"><script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-K7G5DNRH"></script><script src="https://s0.2mdn.net/instream/video/client.js" async="" type="text/javascript"></script><script async="" data-jsonpid="" src="https://cdn-gl.imrworldwide.com/novms/js/2/nlsSDK600.bundle.min.js"></script><script async="" src="https://cdn-gl.imrworldwide.com/conf/config250.js#name=v60Bsdk__1779352521778&amp;ns=NOLBUNDLE"></script><script async="" src="https://sb.scorecardresearch.com/beacon.js"></script><script async="" 0="h" 1="t" 2="t" 3="p" 4="s" 5=":" 6="/" 7="/" 8="b" 9="-" 10="c" 11="o" 12="d" 13="e" 14="." 15="l" 16="i" 17="a" 18="d" 19="m" 20="." 21="c" 22="o" 23="m" 24="/" 25="a" 26="-" 27="0" 28="1" 29="s" 30="i" 31="." 32="m" 33="i" 34="n" 35="." 36="j" 37="s"></script><script async="" src="https://au-script.dotmetrics.net/door.js?d=www.ign.com&amp;t=other"></script><script async="" src="https://securepubads.g.doubleclick.net/tag/js/gpt.js?network-code=5691" referrerpolicy="no-referrer"></script><script async="" src="https://cdn.static.zdbb.net/js/z0WVjCBSEeGLoxIxOQVEwQ.min.js"></script><script async="" src="https://client.aps.amazon-adsystem.com/publisher.js"></script><script async="" id="D4QxaEgV4932fC_gwr4qNIJFm44" src="//cdn.confiant-integrations.net/video/202605191507/wrap.js"></script><script type="text/javascript" async="" src="https://secure-au.imrworldwide.com/v60a.js"></script><script type="text/javascript" async="" src="//static.chartbeat.com/js/chartbeat_video.js"></script><script async="" tag="script" src="https://openads-cdn.adsrvr.org/openadsjs/build/v1.0/ziffdavis/openads.js"></script><script async="" tag="script" src="https://pub.doubleverify.com/dvtag/26327901/DV1293845/pub.js"></script><script async="" tag="script" src="https://cdn.ziffstatic.com/pg/ign.prebid.js"></script><link tag="link" rel="preload" href="https://client.aps.amazon-adsystem.com/publisher.js" as="script"><script id="D4QxaEgV4932fC_gwr4qNIJFm44" async="" src="//cdn.confiant-integrations.net/D4QxaEgV4932fC_gwr4qNIJFm44/video/config.js"></script><script async="" src="//cdn.confiant-integrations.net/gptprebidnative/202605191507/wrap.js"></script><script type="text/javascript" async="" src="https://cdn.confiant-integrations.net/t3dNes-2VKxdhebOtwezHpQAoHM/gpt_and_prebid/config.js"></script><script async="" src="https://config.aps.amazon-adsystem.com/configs/3158"></script><link tag="link" rel="preconnect" href="https://aax.amazon-adsystem.com"><meta charset="utf-8"><title>Track List - Mario Kart World Guide - IGN</title><meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover"><meta name="format-detection" content="telephone=no, date=no, email=no, address=no"><meta name="theme-color" content="#BF1313"><meta name="description" content="There are several brand-new tracks in Mario Kart World, including returning favorites such as Rainbow Road, Mario Circuit, and Bowser&amp;apos;s Castle. This guide"><meta name="robots" content="noodp, noydir, max-image-preview:large"><meta name="bingbot" content="noarchive"><meta property="og:url" content="https://www.ign.com/wikis/mario-kart-world/Track_List"><meta property="og:title" content="Track List - Mario Kart World Guide - IGN"><meta property="og:type" content="website"><meta name="cXenseParse:keywords" content="Mario Kart World,Mario,Mario Kart,Nintendo Switch 2,Action,Racing,Nintendo,Nintendo Entertainment Analysis &amp; Development (EAD),Online Versus Multiplayer,Open-World,Online 24-Player Multiplayer"><meta property="article:published_time" content="2025-06-06T02:24:52Z"><meta property="article:modified_time" content="2025-06-06T09:10:29Z"><meta name="section" content="wiki"><meta property="og:image" content="https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-world/6/6d/Mario_Kart_World_-_Track_Map.png"><meta name="thumbnail" content="https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-world/6/6d/Mario_Kart_World_-_Track_Map.png"><meta property="og:description" content="There are several brand-new tracks in Mario Kart World, including returning favorites such as Rainbow Road, Mario Circuit, and Bowser&amp;apos;s Castle. This guide"><link rel="canonical" href="https://www.ign.com/wikis/mario-kart-world/Track_List"><link rel="alternate" hreflang="x-default" href="https://www.ign.com/wikis/mario-kart-world/Track_List"><link rel="alternate" hreflang="en" href="https://www.ign.com/wikis/mario-kart-world/Track_List"><meta property="al:ios:url" content="ign://ign.com/wikis/mario-kart-world/Track_List"><meta property="al:ios:app_store_id" content="284819997"><meta property="al:ios:app_name" content="IGN: Video Game News, Reviews, Guides"><meta property="al:android:url" content="ign://www.ign.com/wikis/mario-kart-world/Track_List"><meta property="al:android:app_name" content="IGN"><meta property="al:android:package" content="com.mobile.ign"><meta property="al:web:url" content="https://www.ign.com/wikis/mario-kart-world/Track_List"><meta name="twitter:app:name:iphone" content="IGN: Video Game News, Reviews, Guides"><meta name="twitter:app:id:iphone" content="284819997"><meta name="twitter:app:url:iphone" content="ign://www.ign.com/wikis/mario-kart-world/Track_List"><meta name="twitter:app:name:ipad" content="IGN: Video Game News, Reviews, Guides"><meta name="twitter:app:id:ipad" content="284819997"><meta name="twitter:app:url:ipad" content="ign://www.ign.com/wikis/mario-kart-world/Track_List"><meta name="twitter:app:name:googleplay" content="IGN"><meta name="twitter:app:id:googleplay" content="com.mobile.ign"><meta name="twitter:app:url:googleplay" content="ign://www.ign.com/wikis/mario-kart-world/Track_List"><meta name="twitter:card" content="summary"><meta name="twitter:site" content="@IGN"><meta name="twitter:imageUrl" content="https://oyster.ignimgs.com/mediawiki/apis.ign.com/mario-kart-world/6/6d/Mario_Kart_World_-_Track_Map.png"><meta name="facebook-domain-verification" content="960w7qsbsscw9stu2hxr2xfaes6cvc"><link rel="preload" as="script" href="https://cdn.ziffstatic.com/jst/zdconsent.js"><link rel="preload" as="script" href="https://cdn.ziffstatic.com/pg/ign.js"><link rel="preload" as="script" href="https://cdn.ziffstatic.com/pg/ign.prebid.js"><link rel="preload" as="script" href="https://securepubads.g.doubleclick.net/tag/js/gpt.js?network-code=5691"><script type="text/javascript">window.zdconsent = window.zdconsent || {'run': [], 'cmd':[], 'analytics':[], 'functional':[], 'social':[] };</script><script type="text/javascript" id="pogo" src="https://cdn.ziffstatic.com/pg/ign.js" async=""></script><link rel="stylesheet" href="https://cdn.ziffstatic.com/pg/ign.css"><link rel="preload" as="script" href="https://imasdk.googleapis.com/js/sdkloader/ima3.js"><script type="text/javascript" id="zdconsent" src="https://cdn.ziffstatic.com/jst/zdconsent.js" fetchpriority="high" async="" suppresshydrationwarning="true"></script><meta name="next-head-count" content="50"><link rel="shortcut icon" type="image/x-icon" href="https://kraken.ignimgs.com/favicon.ico"><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="copyright" content="IGN Entertainment, Inc."><meta name="referrer" content="always"><meta name="cpid" content="5a8bca0b2d985966302b4671c3a001ee"><meta property="og:site_name" content="IGN"><meta property="fb:app_id" content="115982828429116"><meta property="fb:pages" content="59685491632"><link rel="preload" href="https://apps.ign.com/video-player/fonts/Inter.var-subset.woff2" as="font" type="font/woff2" crossorigin="anonymous"><link rel="stylesheet" href="https://cdn.ziffstatic.com/pg/ign.css"><link rel="preload" as="script" href="https://cdn.static.zdbb.net/js/z0WVjCBSEeGLoxIxOQVEwQ.min.js"><link rel="preload" href="https://kraken.ignimgs.com/_next/static/css/031861d27949a874.css" as="style"><link rel="stylesheet" href="https://kraken.ignimgs.com/_next/static/css/031861d27949a874.css" data-n-g=""><link rel="preload" href="https://kraken.ignimgs.com/_next/static/css/cae7d87e7f2b778f.css" as="style"><link rel="stylesheet" href="https://kraken.ignimgs.com/_next/static/css/cae7d87e7f2b778f.css" data-n-p=""><noscript data-n-css=""></noscript><script defer="" nomodule="" src="https://kraken.ignimgs.com/_next/static/chunks/polyfills-42372ed130431b0a.js"></script><script src="https://kraken.ignimgs.com/_next/static/chunks/webpack-df9da0d0f798e826.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/framework-3701f6f516313524.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/main-236d69f8b51ad415.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/pages/_app-66efd1f5ae13cd79.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/c2772f35-cccbad95d623ae8c.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/b21cdbbe-a620c98a98493448.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/5e1d2776-7b5d7ef1b67b99e4.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/8538-fe6a17e7385a1d7a.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/7943-9d40cf1f7fc730eb.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/49-1f32d0413413d31e.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/1234-a2d7189106f98cf9.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/9984-e796268b70abf413.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/3063-a9579f30eb06b8d7.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/6720-439b2183f65626bb.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/2953-874701f7ebef8afd.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/8887-888e594f51ab8214.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/789-f9ed26439fb81b27.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/8351-862a1db5476924b4.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/4896-b54fff799dbf6217.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/361-0a16b9514c430a66.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/7096-dda18889bca9b7a7.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/8448-f8a537062854acbe.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/1540-cdcb1961ad76c51f.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/7725-5784a165e58fd351.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/1578-b6e939652d19ae53.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/8512-dfecd0294580b63c.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/20-b9bf8a3b3138f322.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/4215-d006fa1a59ba0a0a.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/1489-7a34b055d2041a09.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/4603-601c7c8603048430.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/2000-71f56b26a979ff1a.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/4426-8aa0ed46a0b06082.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/7989-5ec620ab0a07f566.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/650-50dc2c8fb49cc6b6.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/2829-9c5209f1d632b8f1.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/8731-63da40e740464b30.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/7224-a65d2562b982be23.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/834-95884608eda5bcfd.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/9378-8e58eeecad30cb57.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/chunks/pages/wikis/%5Bslug%5D/%5B...chapter%5D-210095a186401efc.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/KU_FytxpY_ELBBZM5olQ_/_buildManifest.js" defer=""></script><script src="https://kraken.ignimgs.com/_next/static/KU_FytxpY_ELBBZM5olQ_/_ssgManifest.js" defer=""></script><meta name="sentry-trace" content="1802860d4ea75f6938db0cdc1c3f12d4-fcccb145e21ee03d"><meta name="baggage" content="sentry-environment=production,sentry-release=kraken%3A%3Av0.97.49,sentry-public_key=258f7434a02a42848a43b89281bddba1,sentry-trace_id=1802860d4ea75f6938db0cdc1c3f12d4"><style id="__jsx-2750866048">.ign-icon.jsx-2750866048{position:relative;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;aspect-ratio:1 / 1;width:1em;height:1em;display:inline-block;-webkit-flex-shrink:0;-ms-flex-negative:0;flex-shrink:0;}</style><style id="__jsx-3782449470">.ign-icon.jsx-3782449470{cursor: inherit;
font-size: 1rem;

In [40]:
# This page has the tracks in an unordered list so let's search for that!
world_soup = BeautifulSoup(world_html)

list_items = world_soup.find_all('li')

# We want the ones that do not contain any tags within them
list_items = [tag.text for tag in list_items if len(tag.find_all()) == 0]

# Remove duplicates
list_items = list(set(list_items))

list_items

['DK Pass',
 'Shy Guy Bazaar',
 'Koopa Troopa Beach',
 'Faraway Oasis',
 'Crown City',
 "Wario's Galleon",
 'Mario Bros. Circuit',
 'Great\xa0? Block Ruins',
 'Mario Circuit',
 'Peach Stadium (Version 1)',
 'Choco Mountain',
 'DK Spaceport',
 'Peach Stadium (Version 2)',
 'Sky-High Sundae',
 "Bowser's Castle",
 'Salty Salty Speedway',
 'Acorn Heights',
 'Cheep Cheep Falls',
 'Airship Fortress',
 'Boo Cinema',
 'Dry Bones Burnout',
 'Crown City (Version 2)',
 'Moo Moo Meadows',
 'Rainbow Road',
 'Starview Peak',
 'Dandelion Depths',
 'Desert Hills',
 'Peach Beach',
 'Peach Stadium',
 'Crown City (Version 1)',
 "Toad's Factory",
 'Whistlestop Summit',
 'Wario Galleon',
 'Dino Dino Jungle',
 'Wario Stadium']

We have all the tracks, but there are a couple of funny ones which we need to clean up

In [47]:
world_raw_df = pd.DataFrame(list_items, columns=['name'])

# Seems some had a couple of versions, so remove version numbers
world_raw_df['name'] = world_raw_df['name'].str.replace(pat=r' \(Version \d\)', repl='', regex=True)

world_raw_df = world_raw_df.drop_duplicates().sort_values(by='name')

print(f"{world_raw_df.shape[0]} tracks found")
world_raw_df

31 tracks found

                    name
16         Acorn Heights
18      Airship Fortress
19            Boo Cinema
14       Bowser's Castle
17     Cheep Cheep Falls
10        Choco Mountain
4             Crown City
0                DK Pass
11          DK Spaceport
25      Dandelion Depths
26          Desert Hills
33      Dino Dino Jungle
20     Dry Bones Burnout
3          Faraway Oasis
7    Great ? Block Ruins
2     Koopa Troopa Beach
6    Mario Bros. Circuit
8          Mario Circuit
22       Moo Moo Meadows
27           Peach Beach
9          Peach Stadium
23          Rainbow Road
15  Salty Salty Speedway
1         Shy Guy Bazaar
13       Sky-High Sundae
24         Starview Peak
30        Toad's Factory
32         Wario Galleon
34         Wario Stadium
5        Wario's Galleon
31    Whistlestop Summit

In [51]:
# There's one double-up due to a misspelling. So we'll just delete it
world_clean_df = world_raw_df.copy()

world_clean_df = world_clean_df[world_clean_df['name'] != 'Wario Galleon']

world_clean_df = world_clean_df.reset_index(drop=True)

print(f"{world_clean_df.shape[0]} tracks found")
world_clean_df

30 tracks found

                    name
0          Acorn Heights
1       Airship Fortress
2             Boo Cinema
3        Bowser's Castle
4      Cheep Cheep Falls
5         Choco Mountain
6             Crown City
7                DK Pass
8           DK Spaceport
9       Dandelion Depths
10          Desert Hills
11      Dino Dino Jungle
12     Dry Bones Burnout
13         Faraway Oasis
14   Great ? Block Ruins
15    Koopa Troopa Beach
16   Mario Bros. Circuit
17         Mario Circuit
18       Moo Moo Meadows
19           Peach Beach
20         Peach Stadium
21          Rainbow Road
22  Salty Salty Speedway
23        Shy Guy Bazaar
24       Sky-High Sundae
25         Starview Peak
26        Toad's Factory
27         Wario Stadium
28       Wario's Galleon
29    Whistlestop Summit

### Saving

Now we have all the tracks, so we can save them!

In [53]:
mk8_track_df = track_df.copy()
world_track_df = world_clean_df.copy()

mk8_track_df['game_version'] = 'Mario Kart 8 Deluxe'
world_track_df['game_version'] = 'Mario Kart World'

all_track_df = pd.concat([mk8_track_df, world_track_df], axis=0)

all_track_df

                   name         game_version
0      Excitebike Arena  Mario Kart 8 Deluxe
1          Electrodrome  Mario Kart 8 Deluxe
2            Water Park  Mario Kart 8 Deluxe
3           Toad Harbor  Mario Kart 8 Deluxe
4   SNES Donut Plains 3  Mario Kart 8 Deluxe
..                  ...                  ...
25        Starview Peak     Mario Kart World
26       Toad's Factory     Mario Kart World
27        Wario Stadium     Mario Kart World
28      Wario's Galleon     Mario Kart World
29   Whistlestop Summit     Mario Kart World

[126 rows x 2 columns]

In [54]:
all_track_df.to_csv(wd / 'data' / 'tracks.csv', index=False)