# Mario Kart Tracker v2: Data Scraping
## Vehicles

The aim of this notebook is to obtain the vehicles for the games and prepare an appropriate CSV file that can then be uploaded to the database.

We will source the vehicles from the Mario Wiki pages. 

Because MK 8 Deluxe has the options for choosing wheels and gliders, we will include those here too (as separate files)

Required libraries:
* `Pandas`
* `BeautifulSoup`
* `Selenium`

In [1]:
# Import required libraries
import pandas as pd
from bs4 import BeautifulSoup, NavigableString, Tag
from selenium import webdriver
from selenium.webdriver.common.by import By
from pathlib import Path

In [2]:
# Set the working directory
wd = Path().cwd()
wd = wd.parent

### Mario Kart 8 Deluxe

Let's start with MK 8. 

We basically need everything on [this page](https://mariokart.fandom.com/wiki/Mario_Kart_8_Deluxe#Vehicle_Parts) in the *Vehicle Parts* section.

For the most part, these are links, though some have an alternative name - this appears to be the name used in Australia (and Europe), so this is what we want for our purposes.

In [3]:
url = "https://mariokart.fandom.com/wiki/Mario_Kart_8_Deluxe"

driver = webdriver.Firefox()
driver.get(url)

mk8_html = driver.page_source

mk8_soup = BeautifulSoup(mk8_html)

driver.quit()

In [4]:
import re

In [5]:
elements = mk8_soup.find_all("h2")
for elem in elements:
    if re.match(r"Vehicle Parts", elem.text):
        section_heading = elem
        break

next_elements = elem.find_all_next(re.compile("h2|h3|table"))
section = None
body_tables = []
glider_tables = []
wheel_tables = []

for elem in next_elements:
    if elem.name == "h3":
        if "Bodies" in elem.text:
            section = "Bodies"
        elif "Wheels" in elem.text:
            section = "Wheels"
        elif "Gliders" in elem.text:
            section = "Gliders"
    elif elem.name == "table":
        if section == "Bodies":
            body_tables.append(elem)
        elif section == "Wheels":
            wheel_tables.append(elem)
        elif section == "Gliders":
            glider_tables.append(elem)
    else:
        break

body_tables

[<table style="text-align:center; margin:auto; font-weight:bold; width:100%">
 <caption>
 </caption>
 <tbody><tr>
 <td width="17%"><span typeof="mw:File"><a href="/wiki/Standard_Kart" title="Standard Kart"><img alt="StandardKartBodyMK8" class="mw-file-element lazyload" data-image-key="StandardKartBodyMK8.png" data-image-name="StandardKartBodyMK8.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/0/05/StandardKartBodyMK8.png/revision/latest/scale-to-width-down/100?cb=20140715154926" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td>
 <td width="17%"><span typeof="mw:File"><a href="/wiki/Pipe_Frame" title="Pipe Frame"><img alt="PipeFrameBodyMK8" class="mw-file-element lazyload" data-image-key="PipeFrameBodyMK8.png" data-image-name="PipeFrameBodyMK8.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/d/d1/PipeFrameBodyMK8.png/revision/latest/scale-to-width-down/100?cb=20141102122932" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td>
 <td width="17%"><span typeof="mw:File"><a href="/wiki/Mach_8" title="Mach 8"><img alt="Mach8BodyMK8" class="mw-file-element lazyload" data-image-key="Mach8BodyMK8.png" data-image-name="Mach8BodyMK8.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/d/df/Mach8BodyMK8.png/revision/latest/scale-to-width-down/100?cb=20141102122956" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td>
 <td width="17%"><span typeof="mw:File"><a href="/wiki/Steel_Driver" title="Steel Driver"><img alt="Steel Driver" class="mw-file-element lazyload" data-image-key="Steel_Driver.png" data-image-name="Steel Driver.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/9/94/Steel_Driver.png/revision/latest/scale-to-width-down/100?cb=20200925190921" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td>
 <td width="17%"><span typeof="mw:File"><a href="/wiki/Cat_Cruiser" title="Cat Cruiser"><img alt="CatCruiserBodyMK8" class="mw-file-element lazyload" data-image-key="CatCruiserBodyMK8.png" data-image-name="CatCruiserBodyMK8.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/f/f4/CatCruiserBodyMK8.png/revision/latest/scale-to-width-down/100?cb=20141102123132" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td>
 <td width="17%"><span typeof="mw:File"><a href="/wiki/Circuit_Special" title="Circuit Special"><img alt="CircuitSpecialBodyMK8" class="mw-file-element lazyload" data-image-key="CircuitSpecialBodyMK8.png" data-image-name="CircuitSpecialBodyMK8.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/6/6c/CircuitSpecialBodyMK8.png/revision/latest/scale-to-width-down/100?cb=20141102123237" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td></tr>
 <tr>
 <td><a href="/wiki/Standard_Kart" title="Standard Kart">Standard Kart</a>*/**
 </td>
 <td><a href="/wiki/Pipe_Frame" title="Pipe Frame">Pipe Frame</a>*
 </td>
 <td><a href="/wiki/Mach_8" title="Mach 8">Mach 8</a>
 </td>
 <td><a href="/wiki/Steel_Driver" title="Steel Driver">Steel Driver</a>**
 </td>
 <td><a href="/wiki/Cat_Cruiser" title="Cat Cruiser">Cat Cruiser</a>
 </td>
 <td><a href="/wiki/Circuit_Special" title="Circuit Special">Circuit Special</a>*/**
 </td></tr>
 <tr>
 <td height="25px">
 </td></tr>
 <tr>
 <td><span typeof="mw:File"><a href="/wiki/Tri-Speeder" title="Tri-Speeder"><img alt="TrispeederBodyMK8" class="mw-file-element lazyload" data-image-key="TrispeederBodyMK8.png" data-image-name="TrispeederBodyMK8.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/5/56/TrispeederBodyMK8.png/revision/latest/scale-to-width-down/100?cb=20141102123217" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td>
 <td><span typeof="mw:File"><a href="/wiki/Badwagon" title="Badwagon"><img alt="BadwagonBodyMK8" class="mw-file-element lazyload" data-image-key="BadwagonBodyMK8.png" data-image-name="BadwagonBodyMK8.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/c/c2/BadwagonBodyMK8.png/revision/latest/scale-to-width-down/100?cb=20141102123350" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td>
 <td><span typeof="mw:File"><a href="/wiki/Prancer" title="Prancer"><img alt="PrancerBodyMK8" class="mw-file-element lazyload" data-image-key="PrancerBodyMK8.png" data-image-name="PrancerBodyMK8.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/f/ff/PrancerBodyMK8.png/revision/latest/scale-to-width-down/100?cb=20141102123333" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td>
 <td><span typeof="mw:File"><a href="/wiki/Biddybuggy" title="Biddybuggy"><img alt="BiddybuggyBodyMK8" class="mw-file-element lazyload" data-image-key="BiddybuggyBodyMK8.png" data-image-name="BiddybuggyBodyMK8.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/4/45/BiddybuggyBodyMK8.png/revision/latest/scale-to-width-down/100?cb=20141102123322" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td>
 <td><span typeof="mw:File"><a href="/wiki/Landship" title="Landship"><img alt="LandshipBodyMK8" class="mw-file-element lazyload" data-image-key="LandshipBodyMK8.png" data-image-name="LandshipBodyMK8.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/6/6d/LandshipBodyMK8.png/revision/latest/scale-to-width-down/100?cb=20141102123656" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td>
 <td><span typeof="mw:File"><a href="/wiki/Sneeker" title="Sneeker"><img alt="SneakerBodyMK8" class="mw-file-element lazyload" data-image-key="SneakerBodyMK8.png" data-image-name="SneakerBodyMK8.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/4/47/SneakerBodyMK8.png/revision/latest/scale-to-width-down/100?cb=20141102123617" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td></tr>
 <tr>
 <td><a href="/wiki/Tri-Speeder" title="Tri-Speeder">Tri-Speeder</a>
 </td>
 <td><a href="/wiki/Badwagon" title="Badwagon">Badwagon</a>
 </td>
 <td>
 <p><a href="/wiki/Prancer" title="Prancer">Prancer</a>
 </p>
 </td>
 <td><a href="/wiki/Biddybuggy" title="Biddybuggy">Biddybuggy</a>*
 </td>
 <td><a href="/wiki/Landship" title="Landship">Landship</a>*
 </td>
 <td><a href="/wiki/Sneeker" title="Sneeker">Sneeker</a>*/**
 </td></tr>
 <tr>
 <td>
 </td>
 <td>
 </td>
 <td>
 </td>
 <td><small><i>Buggybud</i></small>
 </td>
 <td>
 </td>
 <td><small><i>Bounder</i></small>
 </td></tr>
 <tr>
 <td height="25px">
 </td></tr>
 <tr>
 <td><span typeof="mw:File"><a href="/wiki/Sports_Coupe" title="Sports Coupe"><img alt="SportsCoupeMK8" class="mw-file-element lazyload" data-image-key="SportsCoupeMK8.png" data-image-name="SportsCoupeMK8.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/f/f8/SportsCoupeMK8.png/revision/latest/scale-to-width-down/100?cb=20141102123625" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td>
 <td><span typeof="mw:File"><a href="/wiki/Gold_Standard" title="Gold Standard"><img alt="MK8Gold Standard" class="mw-file-element lazyload" data-image-key="MK8Gold_Standard.png" data-image-name="MK8Gold Standard.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/3/31/MK8Gold_Standard.png/revision/latest/scale-to-width-down/100?cb=20141102123637" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td>
 <td><span typeof="mw:File"><a href="/wiki/GLA" title="GLA"><img alt="GLA-MK8" class="mw-file-element lazyload" data-image-key="GLA-MK8.png" data-image-name="GLA-MK8.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/c/c2/GLA-MK8.png/revision/latest/scale-to-width-down/100?cb=20160102140333" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td>
 <td><span typeof="mw:File"><a href="/wiki/W_25_Silver_Arrow" title="W 25 Silver Arrow"><img alt="W25SilverArrow-MK8" class="mw-file-element lazyload" data-image-key="W25SilverArrow-MK8.png" data-image-name="W25SilverArrow-MK8.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/2/25/W25SilverArrow-MK8.png/revision/latest/scale-to-width-down/100?cb=20160102140332" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td>
 <td><span typeof="mw:File"><a href="/wiki/300_SL_Roadster" title="300 SL Roadster"><img alt="300SLRoadster-MK8" class="mw-file-element lazyload" data-image-key="300SLRoadster-MK8.png" data-image-name="300SLRoadster-MK8.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/1/17/300SLRoadster-MK8.png/revision/latest/scale-to-width-down/100?cb=20160102140332" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td>
 <td><span typeof="mw:File"><a href="/wiki/Blue_Falcon" title="Blue Falcon"><img alt="MK8 BlueFalcon" class="mw-file-element lazyload" data-image-key="MK8_BlueFalcon.png" data-image-name="MK8 BlueFalcon.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/e/ed/MK8_BlueFalcon.png/revision/latest/scale-to-width-down/100?cb=20150331235059" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td></tr>
 <tr>
 <td><a href="/wiki/Sports_Coupe" title="Sports Coupe">Sports Coupe</a>
 </td>
 <td><a href="/wiki/Gold_Standard" title="Gold Standard">Gold Standard</a>*****
 </td>
 <td><a href="/wiki/GLA" title="GLA">GLA</a>*
 </td>
 <td><a href="/wiki/W_25_Silver_Arrow" title="W 25 Silver Arrow">W 25 Silver Arrow</a>
 </td>
 <td><a href="/wiki/300_SL_Roadster" title="300 SL Roadster">300 SL Roadster</a>
 </td>
 <td><a href="/wiki/Blue_Falcon" title="Blue Falcon">Blue Falcon</a>
 </td></tr>
 <tr>
 <td>
 </td>
 <td><small><i>Gold Kart</i></small>
 </td></tr>
 <tr>
 <td height="25px">
 </td></tr>
 <tr>
 <td><span typeof="mw:File"><a href="/wiki/Tanooki_Kart" title="Tanooki Kart"><img alt="MK8 TanookiBuggy" class="mw-file-element lazyload" data-image-key="MK8_TanookiBuggy.png" data-image-name="MK8 TanookiBuggy.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/d/d7/MK8_TanookiBuggy.png/revision/latest/scale-to-width-down/100?cb=20150331235545" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td>
 <td><span typeof="mw:File"><a href="/wiki/B_Dasher" title="B Dasher"><img alt="MK8 BDasher" class="mw-file-element lazyload" data-image-key="MK8_BDasher.png" data-image-name="MK8 BDasher.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/3/32/MK8_BDasher.png/revision/latest/scale-to-width-down/100?cb=20150401000836" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td>
 <td><span typeof="mw:File"><a href="/wiki/Streetle" title="Streetle"><img alt="MK8Streetle" class="mw-file-element lazyload" data-image-key="MK8Streetle.png" data-image-name="MK8Streetle.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/c/cf/MK8Streetle.png/revision/latest/scale-to-width-down/100?cb=20150426174005" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td>
 <td><span typeof="mw:File"><a href="/wiki/P-Wing" title="P-Wing"><img alt="MK8PWing" class="mw-file-element lazyload" data-image-key="MK8PWing.png" data-image-name="MK8PWing.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/c/cd/MK8PWing.png/revision/latest/scale-to-width-down/100?cb=20150426174107" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td>
 <td><span typeof="mw:File"><a href="/wiki/Koopa_Clown" title="Koopa Clown"><img alt="MK8DX Koopa Clown" class="mw-file-element lazyload" data-image-key="MK8DX_Koopa_Clown.png" data-image-name="MK8DX Koopa Clown.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/7/70/MK8DX_Koopa_Clown.png/revision/latest/scale-to-width-down/100?cb=20170704061052" decoding="async" height="71" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td>
 <td>
 </td></tr>
 <tr>
 <td><a href="/wiki/Tanooki_Kart" title="Tanooki Kart">Tanooki Kart</a>
 </td>
 <td>
 <p><a class="mw-redirect" href="/wiki/B-Dasher" title="B-Dasher">B-Dasher</a>
 </p>
 </td>
 <td><a href="/wiki/Streetle" title="Streetle">Streetle</a>**
 </td>
 <td>
 <p><a href="/wiki/P-Wing" title="P-Wing">P-Wing</a>
 </p>
 </td>
 <td><a href="/wiki/Koopa_Clown" title="Koopa Clown">Koopa Clown</a>*
 </td>
 <td>
 </td></tr>
 <tr>
 <td><small><i>Tanooki Buggy</i></small>
 </td>
 <td>
 </td>
 <td>
 </td>
 <td>
 </td>
 <td><div style="border-radius:15px; background: linear-gradient(45deg, #1c73cc, #781e31); color:white; width:100px; margin:auto; height:30px"> New
 </div></td>
 <td>
 </td></tr></tbody></table>,
 <table style="text-align:center; margin:auto; font-weight:bold; width:100%">
 <tbody><tr>
 <td width="17%"><span typeof="mw:File"><a href="/wiki/Standard_Bike" title="Standard Bike"><img alt="StandardBikeBodyMK8" class="mw-file-element lazyload" data-image-key="StandardBikeBodyMK8.png" data-image-name="StandardBikeBodyMK8.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/8/84/StandardBikeBodyMK8.png/revision/latest/scale-to-width-down/100?cb=20141102123849" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td>
 <td width="17%"><span typeof="mw:File"><a href="/wiki/Comet" title="Comet"><img alt="CometBodyMK8" class="mw-file-element lazyload" data-image-key="CometBodyMK8.png" data-image-name="CometBodyMK8.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/0/0e/CometBodyMK8.png/revision/latest/scale-to-width-down/100?cb=20141102124024" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td>
 <td width="17%"><span typeof="mw:File"><a href="/wiki/Sport_Bike" title="Sport Bike"><img alt="SportBikeBodyMK8" class="mw-file-element lazyload" data-image-key="SportBikeBodyMK8.png" data-image-name="SportBikeBodyMK8.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/f/fe/SportBikeBodyMK8.png/revision/latest/scale-to-width-down/100?cb=20141102123857" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td>
 <td width="17%"><span typeof="mw:File"><a href="/wiki/The_Duke" title="The Duke"><img alt="TheDukeBodyMK8" class="mw-file-element lazyload" data-image-key="TheDukeBodyMK8.png" data-image-name="TheDukeBodyMK8.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/8/8a/TheDukeBodyMK8.png/revision/latest/scale-to-width-down/100?cb=20200925174819" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td>
 <td width="17%"><span typeof="mw:File"><a href="/wiki/Flame_Rider" title="Flame Rider"><img alt="FlameRiderBodyMK8" class="mw-file-element lazyload" data-image-key="FlameRiderBodyMK8.png" data-image-name="FlameRiderBodyMK8.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/3/31/FlameRiderBodyMK8.png/revision/latest/scale-to-width-down/100?cb=20141102123942" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td>
 <td width="17%"><span typeof="mw:File"><a href="/wiki/Varmint" title="Varmint"><img alt="VarmintBodyMK8" class="mw-file-element lazyload" data-image-key="VarmintBodyMK8.png" data-image-name="VarmintBodyMK8.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/d/d0/VarmintBodyMK8.png/revision/latest/scale-to-width-down/100?cb=20141102123951" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td></tr>
 <tr>
 <td><a href="/wiki/Standard_Bike" title="Standard Bike">Standard Bike</a>*/**
 </td>
 <td><a href="/wiki/Comet" title="Comet">Comet</a>**/***
 </td>
 <td><a href="/wiki/Sport_Bike" title="Sport Bike">Sport Bike</a>*/***
 </td>
 <td><a href="/wiki/The_Duke" title="The Duke">The Duke</a>
 </td>
 <td><a href="/wiki/Flame_Rider" title="Flame Rider">Flame Rider</a>
 </td>
 <td><a href="/wiki/Varmint" title="Varmint">Varmint</a>
 </td></tr>
 <tr>
 <td>
 </td>
 <td>
 </td>
 <td>
 </td>
 <td>
 </td>
 <td>
 </td>
 <td>
 </td></tr>
 <tr>
 <td height="25px">
 </td></tr>
 <tr>
 <td><span typeof="mw:File"><a href="/wiki/Mr._Scooty" title="Mr. Scooty"><img alt="MrScootyBodyMK8" class="mw-file-element lazyload" data-image-key="MrScootyBodyMK8.png" data-image-name="MrScootyBodyMK8.png" data-relevant="0" data-src="https://static.wikia.nocookie.net/mariokart/images/1/18/MrScootyBodyMK8.png/revision/latest/scale-to-width-down/100?cb=20141102123925" decoding="async" height="64" loading="lazy" src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D" width="100"/></a></span>
 </td>

In [6]:
# For each row of each table, we want to check whether it contains images. We don't want the image rows
# These are all contained in <span> tags, so we can look at the first child of each row and then exclude the row if it is a span

rows = []

for table in body_tables:
    data = table.find("tbody")
    for row in data.find_all("tr"):
        if row:
            child = row.find("td")
            grandchild = child.find()
            if grandchild:
                if grandchild.name != "span" and grandchild.name != "div":
                    rows.append(row)
            else:
                rows.append(row)

print(rows)

[<tr>
<td><a href="/wiki/Standard_Kart" title="Standard Kart">Standard Kart</a>*/**
</td>
<td><a href="/wiki/Pipe_Frame" title="Pipe Frame">Pipe Frame</a>*
</td>
<td><a href="/wiki/Mach_8" title="Mach 8">Mach 8</a>
</td>
<td><a href="/wiki/Steel_Driver" title="Steel Driver">Steel Driver</a>**
</td>
<td><a href="/wiki/Cat_Cruiser" title="Cat Cruiser">Cat Cruiser</a>
</td>
<td><a href="/wiki/Circuit_Special" title="Circuit Special">Circuit Special</a>*/**
</td></tr>, <tr>
<td height="25px">
</td></tr>, <tr>
<td><a href="/wiki/Tri-Speeder" title="Tri-Speeder">Tri-Speeder</a>
</td>
<td><a href="/wiki/Badwagon" title="Badwagon">Badwagon</a>
</td>
<td>
<p><a href="/wiki/Prancer" title="Prancer">Prancer</a>
</p>
</td>
<td><a href="/wiki/Biddybuggy" title="Biddybuggy">Biddybuggy</a>*
</td>
<td><a href="/wiki/Landship" title="Landship">Landship</a>*
</td>
<td><a href="/wiki/Sneeker" title="Sneeker">Sneeker</a>*/**
</td></tr>, <tr>
<td>
</td>
<td>
</td>
<td>
</td>
<td><small><i>Buggybud</i></small>
</td>
<td>
</td>
<td><small><i>Bounder</i></small>
</td></tr>, <tr>
<td height="25px">
</td></tr>, <tr>
<td><a href="/wiki/Sports_Coupe" title="Sports Coupe">Sports Coupe</a>
</td>
<td><a href="/wiki/Gold_Standard" title="Gold Standard">Gold Standard</a>*****
</td>
<td><a href="/wiki/GLA" title="GLA">GLA</a>*
</td>
<td><a href="/wiki/W_25_Silver_Arrow" title="W 25 Silver Arrow">W 25 Silver Arrow</a>
</td>
<td><a href="/wiki/300_SL_Roadster" title="300 SL Roadster">300 SL Roadster</a>
</td>
<td><a href="/wiki/Blue_Falcon" title="Blue Falcon">Blue Falcon</a>
</td></tr>, <tr>
<td>
</td>
<td><small><i>Gold Kart</i></small>
</td></tr>, <tr>
<td height="25px">
</td></tr>, <tr>
<td><a href="/wiki/Tanooki_Kart" title="Tanooki Kart">Tanooki Kart</a>
</td>
<td>
<p><a class="mw-redirect" href="/wiki/B-Dasher" title="B-Dasher">B-Dasher</a>
</p>
</td>
<td><a href="/wiki/Streetle" title="Streetle">Streetle</a>**
</td>
<td>
<p><a href="/wiki/P-Wing" title="P-Wing">P-Wing</a>
</p>
</td>
<td><a href="/wiki/Koopa_Clown" title="Koopa Clown">Koopa Clown</a>*
</td>
<td>
</td></tr>, <tr>
<td><small><i>Tanooki Buggy</i></small>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td><div style="border-radius:15px; background: linear-gradient(45deg, #1c73cc, #781e31); color:white; width:100px; margin:auto; height:30px"> New
</div></td>
<td>
</td></tr>, <tr>
<td><a href="/wiki/Standard_Bike" title="Standard Bike">Standard Bike</a>*/**
</td>
<td><a href="/wiki/Comet" title="Comet">Comet</a>**/***
</td>
<td><a href="/wiki/Sport_Bike" title="Sport Bike">Sport Bike</a>*/***
</td>
<td><a href="/wiki/The_Duke" title="The Duke">The Duke</a>
</td>
<td><a href="/wiki/Flame_Rider" title="Flame Rider">Flame Rider</a>
</td>
<td><a href="/wiki/Varmint" title="Varmint">Varmint</a>
</td></tr>, <tr>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td></tr>, <tr>
<td height="25px">
</td></tr>, <tr>
<td><a href="/wiki/Mr._Scooty" title="Mr. Scooty">Mr. Scooty</a>
</td>
<td><a href="/wiki/Jet_Bike" title="Jet Bike">Jet Bike</a>***
</td>
<td><a href="/wiki/Yoshi_Bike" title="Yoshi Bike">Yoshi Bike</a>***
</td>
<td><a href="/wiki/Master_Cycle" title="Master Cycle">Master Cycle</a>***
</td>
<td><a href="/wiki/Master_Cycle_Zero" title="Master Cycle Zero">Master Cycle Zero</a>**/****/*****
</td>
<td><a href="/wiki/City_Tripper" title="City Tripper">City Tripper</a>*/**
</td></tr>, <tr>
<td><small><i>Mr Scooty</i></small>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td><div style="border-radius:15px; background: linear-gradient(45deg, #1c73cc, #781e31); color:white; width:100px; margin:auto; height:30px"> New
</div></td></tr>, <tr>
<td><a href="/wiki/Standard_ATV" title="Standard ATV">Standard ATV</a>*/**
</td>
<td><a href="/wiki/Wild_Wiggler" title="Wild Wiggler">Wild Wiggler</a>
</td>
<td><a href="/wiki/Teddy_Buggy" title="Teddy Buggy">Teddy Buggy</a>
</td>
<td><a href="/wiki/Bone_Rattler" title="Bone Rattler">Bone Rattler</a>
</td>
<td><a href="/wiki/Splat_Buggy" title="Splat Buggy">Splat Buggy</a>*/**
</td>
<td>
<p><a href="/wiki/Inkstriker" title="Inkstriker">Inkstriker</a>*/**
</p>
</td></tr>, <tr>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td><div style="border-radius:15px; background: linear-gradient(45deg, #1c73cc, #781e31); color:white; width:100px; margin:auto; height:30px"> New
</div></td>
<td>
<div style="border-radius:15px; background: linear-gradient(45deg, #1c73cc, #781e31); color:white; width:100px; margin:auto; height:30px"> New
</div></td></tr>]

In [7]:
import numpy as np

In [8]:
row = rows[3]

for child in row.children:
    if isinstance(child, NavigableString):
        continue
    elif isinstance(child, Tag):
        small = child.select('small')
        print(small)

[]
[]
[]
[<small><i>Buggybud</i></small>]
[]
[<small><i>Bounder</i></small>]

In [9]:
rows_simplified = []

for row in rows:
    row_simplified = []
    for child in row.children:
        if isinstance(child, NavigableString):
            continue
        
        # If there is an alternative name, it will be in small italics
        # Check for this
        small = child.select('small')
        if small:
            value = child.text.rstrip("\n*/ ").lstrip("\n ") + " [AUS]"
        else:
            value = child.text.rstrip("\n*/ ").lstrip("\n ")

        if value in {"", "New"}:
            row_simplified.append(np.nan)
        else:
            row_simplified.append(value)
    
    rows_simplified.append(row_simplified)

body_df = pd.DataFrame(rows_simplified)

body_df = body_df.dropna(axis=1, how="all")
body_df = body_df.dropna(axis=0, how="all")

body_df = body_df.reset_index(drop=True)

body_df

,0,1,2,3,4,5
0,Standard Kart,Pipe Frame,Mach 8,Steel Driver,Cat Cruiser,Circuit Special
1,Tri-Speeder,Badwagon,Prancer,Biddybuggy,Landship,Sneeker
2,NaN,NaN,NaN,Buggybud [AUS],NaN,Bounder [AUS]
3,Sports Coupe,Gold Standard,GLA,W 25 Silver Arrow,300 SL Roadster,Blue Falcon
4,NaN,Gold Kart [AUS],NaN,NaN,NaN,NaN
5,Tanooki Kart,B-Dasher,Streetle,P-Wing,Koopa Clown,NaN
6,Tanooki Buggy [AUS],NaN,NaN,NaN,NaN,NaN
7,Standard Bike,Comet,Sport Bike,The Duke,Flame Rider,Varmint
8,Mr. Scooty,Jet Bike,Yoshi Bike,Master Cycle,Master Cycle Zero,City Tripper
9,Mr Scooty [AUS],NaN,NaN,NaN,NaN,NaN
10,Standard ATV,Wild Wiggler,Teddy Buggy,Bone Rattler,Splat Buggy,Inkstriker

In [10]:
import math

In [27]:
wrangled_df = body_df.copy()

for row in range(0, len(body_df) - 1):
    next_row_contains_aus_names = False
    for col in wrangled_df.columns:
        value = wrangled_df.loc[row, col]
        next_value = wrangled_df.loc[row + 1, col]

        if isinstance(value, str) and isinstance(next_value, str):
            if "[AUS]" in next_value:
                next_row_contains_aus_names = True
                wrangled_df.loc[row, col] = next_value.replace("[AUS]", "")

    # Fill the first row with "False", since it won't have Aus. names
    if row == 0:
        wrangled_df.loc[row, "Contains Aus. Names"] = False

    wrangled_df.loc[row + 1, "Contains Aus. Names"] = next_row_contains_aus_names

wrangled_df = wrangled_df[wrangled_df["Contains Aus. Names"] == False]
wrangled_df = wrangled_df.drop(columns=["Contains Aus. Names"])

body_values = [list(row) for row in list(wrangled_df.values)]
body_values = list(set([val for row in body_values for val in row]))

body_final_df = pd.DataFrame(body_values)
body_final_df = body_final_df[body_final_df[0].notna()]
body_final_df

                    0
0         Teddy Buggy
1         Tri-Speeder
3            Bounder
4             Varmint
5          Sport Bike
6          Mr Scooty
7        Master Cycle
8               Comet
9           Buggybud
10         Pipe Frame
11            Prancer
12       Standard ATV
13      Standard Kart
14        Blue Falcon
15           Badwagon
16     Tanooki Buggy
17           Streetle
18    300 SL Roadster
19         Yoshi Bike
20       Steel Driver
21             Mach 8
22           Landship
23        Flame Rider
24        Splat Buggy
25       Wild Wiggler
26        Koopa Clown
27        Cat Cruiser
28                GLA
29             P-Wing
30       City Tripper
31       Bone Rattler
32           The Duke
33    Circuit Special
34         Inkstriker
35  W 25 Silver Arrow
36           Jet Bike
37  Master Cycle Zero
38         Gold Kart
39           B-Dasher
40       Sports Coupe
41      Standard Bike

### Wheels and Gliders

Now that we have the bodies, let's sort out the wheels and gliders.

We can largely do the same as we did for the bodies, as the sections are structured quite similarly.

In [29]:
rows = []
rows_simplified = []

for table in glider_tables:
    data = table.find("tbody")
    for row in data.find_all("tr"):
        if row:
            child = row.find("td")
            grandchild = child.find()
            if grandchild:
                if grandchild.name != "span" and grandchild.name != "div":
                    rows.append(row)
            else:
                rows.append(row)

for row in rows:
    row_simplified = []
    for child in row.children:
        if isinstance(child, NavigableString):
            continue
        
        # If there is an alternative name, it will be in small italics
        # Check for this
        small = child.select('small')
        if small:
            value = child.text.rstrip("\n*/ ").lstrip("\n ") + " [AUS]"
        else:
            value = child.text.rstrip("\n*/ ").lstrip("\n ")

        if value in {"", "New"}:
            row_simplified.append(np.nan)
        else:
            row_simplified.append(value)
    
    rows_simplified.append(row_simplified)

glider_df = pd.DataFrame(rows_simplified)

glider_df = glider_df.dropna(axis=1, how="all")
glider_df = glider_df.dropna(axis=0, how="all")

glider_df = glider_df.reset_index(drop=True)

wrangled_df = glider_df.copy()

for row in range(0, len(glider_df) - 1):
    next_row_contains_aus_names = False
    for col in wrangled_df.columns:
        value = wrangled_df.loc[row, col]
        next_value = wrangled_df.loc[row + 1, col]

        if isinstance(value, str) and isinstance(next_value, str):
            if "[AUS]" in next_value:
                next_row_contains_aus_names = True
                wrangled_df.loc[row, col] = next_value.replace("[AUS]", "")

    # Fill the first row with "False", since it won't have Aus. names
    if row == 0:
        wrangled_df.loc[row, "Contains Aus. Names"] = False

    wrangled_df.loc[row + 1, "Contains Aus. Names"] = next_row_contains_aus_names

wrangled_df = wrangled_df[wrangled_df["Contains Aus. Names"] == False]
wrangled_df = wrangled_df.drop(columns=["Contains Aus. Names"])

glider_values = [list(row) for row in list(wrangled_df.values)]
glider_values = list(set([val for row in glider_values for val in row]))

glider_final_df = pd.DataFrame(glider_values)
glider_final_df = glider_final_df[glider_final_df[0].notna()]
glider_final_df = glider_final_df.rename(columns={0: 'name'})
glider_final_df

                0
0    Plane Glider
1   MKTV Parafoil
3    Cloud Glider
4       Parachute
5      Wario Wing
6   Peach Parasol
7     Hylian Kite
8    Super Glider
9     Gold Glider
10   Paper Glider
11       Parafoil
12     Paraglider
13    Bowser Kite
14  Flower Glider
15    Waddle Wing

Now we do the wheels

In [30]:
rows = []
rows_simplified = []

for table in wheel_tables:
    data = table.find("tbody")
    for row in data.find_all("tr"):
        if row:
            child = row.find("td")
            grandchild = child.find()
            if grandchild:
                if grandchild.name != "span" and grandchild.name != "div":
                    rows.append(row)
            else:
                rows.append(row)

for row in rows:
    row_simplified = []
    for child in row.children:
        if isinstance(child, NavigableString):
            continue
        
        # If there is an alternative name, it will be in small italics
        # Check for this
        small = child.select('small')
        if small:
            value = child.text.rstrip("\n*/ ").lstrip("\n ") + " [AUS]"
        else:
            value = child.text.rstrip("\n*/ ").lstrip("\n ")

        if value in {"", "New"}:
            row_simplified.append(np.nan)
        else:
            row_simplified.append(value)
    
    rows_simplified.append(row_simplified)

wheel_df = pd.DataFrame(rows_simplified)

wheel_df = wheel_df.dropna(axis=1, how="all")
wheel_df = wheel_df.dropna(axis=0, how="all")

wheel_df = wheel_df.reset_index(drop=True)

wrangled_df = wheel_df.copy()

for row in range(0, len(wheel_df) - 1):
    next_row_contains_aus_names = False
    for col in wrangled_df.columns:
        value = wrangled_df.loc[row, col]
        next_value = wrangled_df.loc[row + 1, col]

        if isinstance(value, str) and isinstance(next_value, str):
            if "[AUS]" in next_value:
                next_row_contains_aus_names = True
                wrangled_df.loc[row, col] = next_value.replace("[AUS]", "")

    # Fill the first row with "False", since it won't have Aus. names
    if row == 0:
        wrangled_df.loc[row, "Contains Aus. Names"] = False

    wrangled_df.loc[row + 1, "Contains Aus. Names"] = next_row_contains_aus_names

wrangled_df = wrangled_df[wrangled_df["Contains Aus. Names"] == False]
wrangled_df = wrangled_df.drop(columns=["Contains Aus. Names"])

wheel_values = [list(row) for row in list(wrangled_df.values)]
wheel_values = list(set([val for row in wheel_values for val in row]))

wheel_final_df = pd.DataFrame(wheel_values)
wheel_final_df = wheel_final_df[wheel_final_df[0].notna()]
wheel_final_df = wheel_final_df.rename(columns={0: 'name'})
wheel_final_df

                  0
0    Funky Monster
2      Crimson Slim
3    Ancient Tyres
4   Triforce Tyres
5             Slick
6             Metal
7       GLA Wheels
8           Cushion
9      Gold Wheels
10           Sponge
11          Monster
12          Normal
13         Off-Road
14      Leaf Tyres
15      Cyber Slick
16           Button
17     Azure Roller
18   Retro Off-Road
19          Wooden
20           Roller
21     Normal Blue
22             Slim

We don't need gliders or wheels for MK World, so we'll just save now

In [ ]:
glider_final_df.to_csv(wd / 'data' / 'gliders.csv', index=False)
wheel_final_df.to_csv(wd / 'data' / 'wheels.csv', index=False)

## Mario Kart World

Now let's get the Mario Kart World vehicles

In [110]:
url = "https://www.ign.com/wikis/mario-kart-world/All_Vehicles_List_and_Stats_Explained"

driver = webdriver.Firefox()
driver.get(url)

mkw_html = driver.page_source

mkw_soup = BeautifulSoup(mkw_html)

driver.quit()

In [116]:
elements = mkw_soup.find_all(class_="jsx-3850324473 jsx-3179845851 jsx-28683165 wiki-section wiki-html")

all_tables = []

for elem in elements:
    tables = elem.find_all("table")
    all_tables.extend(tables)

print(f"{len(all_tables)} tables found")

1 tables found

Found only one table, which is the one we want, so let's use that one (conveniently also uses the European/Australian names)

In [162]:
table = all_tables[0]

table = table.find("tbody")

rows = table.find_all("tr")

all_values = []

for row in rows:
    values = [val.text.rstrip("\n\t") for val in row.children]
    all_values.append(values)

mkw_vehicle_df = pd.DataFrame(all_values)

mkw_vehicle_df = mkw_vehicle_df[(mkw_vehicle_df[0] != "") & 
                                (mkw_vehicle_df[0] != "Available at the start") &
                                (mkw_vehicle_df[0] != "Unlocked with coins")]

mkw_vehicle_values = [list(row) for row in list(mkw_vehicle_df.values)]
mkw_vehicle_values = list(set([val for row in mkw_vehicle_values for val in row]))

mkw_final_df = pd.DataFrame(mkw_vehicle_values)
mkw_final_df = mkw_final_df[mkw_final_df[0].notna()]
mkw_final_df.columns = ['vehicle_name']

print(f"{len(mkw_final_df)} vehicles found")
mkw_final_df.sort_values(by='vehicle_name')

41 vehicles found

       vehicle_name
3          B Dasher
32     Baby Blooper
21         Big Horn
5         Billdozer
34  Blastronaut III
17   Bowser Bruiser
24         Buggybud
11         Bumble V
26     Carpet Flyer
1    Chargin' Truck
31          Cloud 9
6        Cute Scoot
19   Dolphin Dasher
7        Dread Sled
30         Fin Twin
12     Funky Dorrie
28          Hot Rod
36       Hyper Pipe
29     Junkyard Hog
41       Li'l Dumpy
8    Lobster Roller
2         Loco Moto
15      Mach Rocket
35      Mecha Trike
23       Pipe Frame
18       Plushbuggy
10    R.O.B. H.O.G.
37      R.O.B.H.O.G
27       Rally Bike
33       Rally Kart
38     Rally Romper
39       Rallygator
25       Reel Racer
16   Ribbit Revster
20  Roadster Royale
40    Standard Bike
9     Standard Kart
13    Stelllar Sled
0      Tune Thumper
14   W-Twin Chopper
4        Zoom Buggy

There are 41 results, but there should only be 40. Let's compare all the strings so we can see which are the most similar in case there are a few duplicates

In [139]:
import Levenshtein

In [154]:
tmp_df1 = mkw_final_df.copy()
tmp_df2 = mkw_final_df.copy()

tmp_df1['key'] = 0
tmp_df2['key'] = 0

full_df = tmp_df1.merge(tmp_df2, on='key', how='outer')

full_df = full_df.drop(columns=['key'])

full_df['sim'] = full_df.apply(lambda row: Levenshtein.ratio(row['vehicle_name_x'], row['vehicle_name_y']), axis=1)

full_df[full_df['sim'] < 1].sort_values(by='sim', ascending=False)

     vehicle_name_x  vehicle_name_y       sim
446   R.O.B. H.O.G.     R.O.B.H.O.G  0.916667
1486    R.O.B.H.O.G   R.O.B. H.O.G.  0.916667
1350     Rally Kart      Rallygator  0.700000
1590     Rallygator      Rally Kart  0.700000
408   Standard Kart   Standard Bike  0.692308
...             ...             ...       ...
965        Buggybud      Pipe Frame  0.000000
962        Buggybud  Dolphin Dasher  0.000000
972        Buggybud        Fin Twin  0.000000
967        Buggybud      Reel Racer  0.000000
1676     Li'l Dumpy     R.O.B.H.O.G  0.000000

[1640 rows x 3 columns]

Looks like there's a duplicate in "R.O.B.H.O.G" and "R.O.B. H.O.G"

In [163]:
mkw_deduplicate_df = mkw_final_df.copy()

mkw_deduplicate_df = mkw_deduplicate_df[mkw_deduplicate_df["vehicle_name"] != "R.O.B. H.O.G."]

mkw_deduplicate_df = mkw_deduplicate_df.reset_index(drop=True)

print(f"{len(mkw_deduplicate_df)} vehicles found")
mkw_deduplicate_df

40 vehicles found

       vehicle_name
0      Tune Thumper
1    Chargin' Truck
2         Loco Moto
3          B Dasher
4        Zoom Buggy
5         Billdozer
6        Cute Scoot
7        Dread Sled
8    Lobster Roller
9     Standard Kart
10         Bumble V
11     Funky Dorrie
12    Stelllar Sled
13   W-Twin Chopper
14      Mach Rocket
15   Ribbit Revster
16   Bowser Bruiser
17       Plushbuggy
18   Dolphin Dasher
19  Roadster Royale
20         Big Horn
21       Pipe Frame
22         Buggybud
23       Reel Racer
24     Carpet Flyer
25       Rally Bike
26          Hot Rod
27     Junkyard Hog
28         Fin Twin
29          Cloud 9
30     Baby Blooper
31       Rally Kart
32  Blastronaut III
33      Mecha Trike
34       Hyper Pipe
35      R.O.B.H.O.G
36     Rally Romper
37       Rallygator
38    Standard Bike
39       Li'l Dumpy

Now we have the right number.

Now let's combine the two lots into one dataframe that we can save

In [167]:
mk8_df = body_final_df.copy()
mkw_df = mkw_deduplicate_df.copy()

mk8_df.columns = ['vehicle_name']

mk8_df['game'] = 'Mario Kart 8 Deluxe'
mkw_df['game'] = 'Mario Kart World'

mk_vehicles = pd.concat([mk8_df, mkw_df])

mk_vehicles.to_csv(wd / 'data' / 'vehicles.csv', index=False)

mk_vehicles

         vehicle_name                 game
0            B-Dasher  Mario Kart 8 Deluxe
1        Master Cycle  Mario Kart 8 Deluxe
2     300 SL Roadster  Mario Kart 8 Deluxe
3   Master Cycle Zero  Mario Kart 8 Deluxe
4            Landship  Mario Kart 8 Deluxe
..                ...                  ...
35        R.O.B.H.O.G     Mario Kart World
36       Rally Romper     Mario Kart World
37         Rallygator     Mario Kart World
38      Standard Bike     Mario Kart World
39         Li'l Dumpy     Mario Kart World

[75 rows x 2 columns]